'use client'

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'
import { additionalTranslations } from './translations'

type Language = 'es' | 'pt' | 'en'

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    'Belleza que nace de la tradición. Cosmética que transforma.': 'Belleza que nace de la tradición. Cosmética que transforma.',
    'Envíos para toda América Latina': 'Envíos para toda América Latina',
    'Atención': 'Atención',
    'Inicio': 'Inicio',
    'Tienda': 'Tienda',
    'Rutinas': 'Rutinas',
    'Blog': 'Blog',
    'Experiencias': 'Experiencias',
    'Buscar...': 'Buscar...',
    'Entrar': 'Iniciar Sesión',
    'Crear Cuenta': 'Crear Cuenta',
    'Mi Panel': 'Mi Panel',
    'Cerrar Sesión': 'Cerrar Sesión',
    'Categorías': 'Categorías',
    'Productos': 'Productos',
    'Sesión': 'Sesión',
    'Español': 'Español',
    'Portugués': 'Portugués',
    'Inglés': 'Inglés',
    // Footer
    'Todos los derechos reservados': 'Todos los derechos reservados',
    'Orgulhosamente desenvolvido por': 'Desarrollado orgullosamente por',
    'En colaboración con': 'En colaboración con',
    // Home
    'Tu belleza.': 'Tu belleza.',
    'Tu ritual.': 'Tu ritual.',
    'Tu momento.': 'Tu momento.',
    'CHEOTNUN — Tu tienda online de cosmética coreana K-Beauty': 'CHEOTNUN — Tu tienda online de cosmética coreana K-Beauty',
    'Cheotnun es tu tienda online de cosmética coreana K-Beauty. Compra productos auténticos, descubre rutinas personalizadas para tu tipo de piel y recibe envíos a toda América Latina.': 'Cheotnun es tu tienda online de cosmética coreana K-Beauty. Compra productos auténticos, descubre rutinas personalizadas para tu tipo de piel y recibe envíos a toda América Latina.',
    'COMPRAR AHORA': 'COMPRAR AHORA',
    'DESCUBRIR RUTINAS': 'DESCUBRIR RUTINAS',
    'Colección Curada': 'Colección Curada',
    'Descubre lo mejor del K-Beauty': 'Descubre lo mejor del K-Beauty',
    'Productos auténticos para realzar tu belleza natural.': 'Productos auténticos para realzar tu belleza natural.',
    'VER TODAS LAS CATEGORÍAS': 'VER TODAS LAS CATEGORÍAS',
    'Favoritos de la Comunidad': 'Favoritos de la Comunidad',
    'Más vendidos': 'Más vendidos',
    'Los favoritos de nuestra comunidad internacional. Fórmulas probadas que entregan resultados visibles.': 'Los favoritos de nuestra comunidad internacional. Fórmulas probadas que entregan resultados visibles.',
    'VER TODOS': 'VER TODOS',
    'Experiencias Cheotnun': 'Experiencias Cheotnun',
    'Vive la belleza coreana más allá de los productos': 'Vive la belleza coreana más allá de los productos',
    'SABER MÁS': 'SABER MÁS',
    'Tratamientos Específicos': 'Tratamientos Específicos',
    'Rutinas para cada necesidad': 'Rutinas para cada necesidad',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.',
    'VER TODAS LAS RUTINAS': 'VER TODAS LAS RUTINAS',
    'Únete a nuestra comunidad': 'Únete a nuestra comunidad',
    'Tips, rutinas, lanzamientos y mucho más en Instagram.': 'Tips, rutinas, lanzamientos y mucho más en Instagram.',
    'SEGUIR EN INSTAGRAM': 'SEGUIR EN INSTAGRAM',
    'Ingredientes seguros': 'Ingredientes seguros',
    'Fórmulas efectivas': 'Fórmulas efectivas',
    'Resultados reales': 'Resultados reales',
    'Inspirado en la tradición': 'Inspirado en la tradición',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'Suscríbete y recibe un 10% de descuento': 'Suscríbete y recibe un 10% de descuento',
    'Tu correo electrónico': 'Tu correo electrónico',
    'SUSCRIBIRSE': 'SUSCRIBIRSE',
    '✓ ¡Te has suscrito con éxito! Bienvenido al Cheotnun Club.': '✓ ¡Te has suscrito con éxito! Bienvenido al Cheotnun Club.',
    // Tienda
    'Tienda Cheotnun': 'Tienda Cheotnun',
    'Todos los Productos': 'Todos los Productos',
    'Filtrar': 'Filtrar',
    'Ordenar': 'Ordenar',
    'Más Recientes': 'Más Recientes',
    'Menor Precio': 'Menor Precio',
    'Mayor Precio': 'Mayor Precio',
    'Más Vendidos': 'Más Vendidos',
    'Agregar al Carrito': 'Agregar al Carrito',
    'Ver Detalles': 'Ver Detalles',
    'Sin stock': 'Sin Stock',
    'Categoría': 'Categoría',
    'Marca': 'Marca',
    'Precio': 'Precio',
    'Buscar productos...': 'Buscar productos...',
    'No hay productos': 'No hay productos',
    'Tu carrito está vacío': 'Tu carrito está vacío',
    'Ir a la Tienda': 'Ir a la Tienda',
    'Carrito': 'Carrito',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Finalizar Compra',
    'Continuar Comprando': 'Continuar Comprando',
    'Eliminar': 'Eliminar',
    'Cantidad': 'Cantidad',
    'Total': 'Total',
    'Envío calculado en el checkout': 'Envío calculado en el checkout',
    // Rutinas
    'Rutinas de Skincare': 'Rutinas de Skincare',
    'Rutina de': 'Rutina de',
    'Productos para': 'Productos para',
    'Ver Productos': 'Ver Productos',
    // Blog
    'Blog Cheotnun K-Beauty': 'Blog Cheotnun K-Beauty',
    'Últimos Artículos': 'Últimos Artículos',
    'Leer más': 'Leer más',
    'Publicado en': 'Publicado en',
    'Por': 'Por',
    'Volver al Blog': 'Volver al Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'CHEOTNUN EXPERIENCE',
    'EN COLABORACIÓN CON MAEUM': 'EN COLABORACIÓN CON MAEUM',
    'BEAUTY & CULTURA': 'BEAUTY & CULTURA',
    'EXPLORAR VIAJES': 'EXPLORAR VIAJES',
    'VER EXPERIENCIAS': 'VER EXPERIENCIAS',
    'Experiencias Exclusivas K-Beauty': 'Experiencias Exclusivas K-Beauty',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Descubre el verdadero arte del skincare coreano',
    'EXPLORAR EL CATÁLOGO': 'EXPLORAR EL CATÁLOGO',
    'Inmersión y Bienestar': 'Inmersión y Bienestar',
    'Más allá del Producto:': 'Más allá del Producto:',
    'Una Filosofía de Cuidado': 'Una Filosofía de Cuidado',
    'Programas de Inmersión Seleccionados': 'Programas de Inmersión Seleccionados',
    'Reservar Plaza': 'Reservar Plaza',
    'Inversión': 'Inversión',
    '¿Por qué elegirnos?': '¿Por qué elegirnos?',
    'Beneficios de la Inmersión Cheotnun': 'Beneficios de la Inmersión Cheotnun',
    'Certificación Premium': 'Certificación Premium',
    'Inmersión Cultural': 'Inmersión Cultural',
    'Asesoría de por vida': 'Asesoría de por vida',
    'Cómo participar del programa': 'Cómo participar del programa',
    'Paso a Paso': 'Paso a Paso',
    'Selecciona tu Experiencia': 'Selecciona tu Experiencia',
    'Reserva & Cuestionario': 'Reserva & Cuestionario',
    'Asesoría Individual': 'Asesoría Individual',
    'Vive la Experiencia': 'Vive la Experiencia',
    '¿Dudas?': '¿Dudas?',
    '¿Quieres una Experiencia Privada?': '¿Quieres una Experiencia Privada?',
    'HABLAR CON CONSULTORA': 'HABLAR CON CONSULTORA',
    'Recibe invitaciones a nuevos talleres': 'Recibe invitaciones a nuevos talleres',
    // Dashboard
    'Mi Cuenta': 'Mi Cuenta',
    'Mis Pedidos': 'Mis Pedidos',
    'Mis Favoritos': 'Mis Favoritos',
    'Mis Datos': 'Mis Datos',
    'Direcciones': 'Direcciones',
    'Club Cheotnun': 'Club Cheotnun',
    'Configuración': 'Configuración',
    'Bienvenido/a': 'Bienvenido/a',
    'Email': 'Email',
    'Teléfono': 'Teléfono',
    'Actualizar Datos': 'Actualizar Datos',
    'Guardar': 'Guardar',
    'Cancelar': 'Cancelar',
    'Nombre': 'Nombre',
    'Apellido': 'Apellido',
    'Fecha de Nacimiento': 'Fecha de Nacimiento',
    'Género': 'Género',
    'Femenino': 'Femenino',
    'Masculino': 'Masculino',
    'Otro': 'Otro',
    // Auth
    '¿Olvidaste tu contraseña?': '¿Olvidaste tu contraseña?',
    'Recuperar Contraseña': 'Recuperar Contraseña',
    'Ingresa tu email': 'Ingresa tu email',
    'Enviar': 'Enviar',
    'Volver al Login': 'Volver al Login',
    'Crear tu cuenta': 'Crear tu cuenta',
    'Registrarme': 'Registrarme',
    'Ya tengo cuenta': 'Ya tengo cuenta',
    'Al menos 6 caracteres': 'Al menos 6 caracteres',
    'Confirmar contraseña': 'Confirmar contraseña',
    'He leído y acepto los': 'He leído y acepto los',
    'Términos y Condiciones': 'Términos y Condiciones',
    'Política de Privacidad': 'Política de Privacidad',
    // Erros e Sucesso
    'Error': 'Error',
    'Éxito': 'Éxito',
    'Cargando...': 'Cargando...',
    'Producto agregado al carrito': 'Producto agregado al carrito',
    'Producto eliminado del carrito': 'Producto eliminado del carrito',
    'Producto agregado a favoritos': 'Producto agregado a favoritos',
    'Producto eliminado de favoritos': 'Producto eliminado de favoritos',
    // Tienda textos
    'agregado al carrito': 'agregado al carrito',
    'Catálogo de Cosméticos': 'Catálogo de Cosméticos',
    'Todas las categorías': 'Todas las categorías',
    'Todas las marcas': 'Todas las marcas',
    'Buscar Producto': 'Buscar Producto',
    'Ej: Sérum, Limpiador...': 'Ej: Sérum, Limpiador...',
    'Marcas': 'Marcas',
    'Filtrar por': 'Filtrar por',
    'Ordenar por': 'Ordenar por',
    'Precio: Menor a Mayor': 'Precio: Menor a Mayor',
    'Precio: Mayor a Menor': 'Precio: Mayor a Menor',
    'Más recientes': 'Más recientes',
    'Nombre: A-Z': 'Nombre: A-Z',
    'Nombre: Z-A': 'Nombre: Z-A',
    'Sin resultados': 'Sin resultados',
    'No se encontraron productos': 'No se encontraron productos',
    'Intenta con otros filtros': 'Intenta con otros filtros',
    'Ver Producto': 'Ver Producto',
    'Producto': 'Producto',
    'Detalles': 'Detalles',
    'Descripción': 'Descripción',
    'Información': 'Información',
    'Ingredientes': 'Ingredientes',
    'Modo de uso': 'Modo de uso',
    'Beneficios': 'Beneficios',
    'Características': 'Características',
    'Opiniones': 'Opiniones',
    'Reseñas': 'Reseñas',
    'Calificación': 'Calificación',
    'Escribir opinión': 'Escribir opinión',
    'Enviar opinión': 'Enviar opinión',
    'Tu opinión': 'Tu opinión',
    'Opiniones de clientes': 'Opiniones de clientes',
    'Producto relacionado': 'Producto relacionado',
    'Productos relacionados': 'Productos relacionados',
    'Te puede interesar': 'Te puede interesar',
    'Ver todos': 'Ver todos',
    'Volver': 'Volver',
    'Anterior': 'Anterior',
    'Siguiente': 'Siguiente',
    'Página': 'Página',
    'de': 'de',
    // Header completo
    'Belleza que nace': 'Belleza que nace',
    'tradición': 'tradición',
    'Cosmética que transforma': 'Cosmética que transforma',
    'Envíos para toda': 'Envíos para toda',
    'América Latina': 'América Latina',
    'Buscar': 'Buscar',
    'Panel': 'Panel',
    'Salir': 'Salir',
    'Favoritos': 'Favoritos',
    'Ver carrito': 'Ver carrito',
    'Tu carrito': 'Tu carrito',
    'vacío': 'vacío',
    'Continuar': 'Continuar',
    'Comprar': 'Comprar',
    'Ofertas': 'Ofertas',
    'Novedades': 'Novedades',
    'Colecciones': 'Colecciones',
    'Sets': 'Sets',
    'Kits': 'Kits',
    'Regalos': 'Regalos',
    'Tarjeta Regalo': 'Tarjeta Regalo',
    'Ayuda': 'Ayuda',
    'Envíos': 'Envíos',
    'Devoluciones': 'Devoluciones',
    'FAQ': 'FAQ',
    'Contacto': 'Contacto',
    'Sobre Nosotros': 'Sobre Nosotros',
    'Nuestra Historia': 'Nuestra Historia',
    'Sostenibilidad': 'Sostenibilidad',
    'Skin Care': 'Skin Care',
    'Maquillaje': 'Maquillaje',
    'Cabello': 'Cabello',
    'Cuerpo': 'Cuerpo',
    'Solares': 'Solares',
    'Hombres': 'Hombres',
    'Niños': 'Niños',
    'Profesionales': 'Profesionales',
    'Salón': 'Salón',
    'Spa': 'Spa',
    // Banner Hero
    'Tu belleza': 'Tu belleza',
    'Tu ritual': 'Tu ritual',
    'Tu momento': 'Tu momento',
    'Cosméticos coreanos': 'Cosméticos coreanos',
    'auténticos': 'auténticos',
    'seleccionados': 'seleccionados',
    'cada etapa': 'cada etapa',
    'cuidado facial': 'cuidado facial',
    'Fórmulas botánicas': 'Fórmulas botánicas',
    'revelan': 'revelan',
    'luminosidad natural': 'luminosidad natural',
    'COMPRAR': 'COMPRAR',
    'AHORA': 'AHORA',
    'DESCUBRIR': 'DESCUBRIR',
    'RUTINAS': 'RUTINAS',
    // Seções Home
    'Colección': 'Colección',
    'Curada': 'Curada',
    'Descubre': 'Descubre',
    'mejor': 'mejor',
    'K-Beauty': 'K-Beauty',
    'realzar': 'realzar',
    'belleza natural': 'belleza natural',
    'VER': 'VER',
    'TODAS': 'TODAS',
    'LAS': 'LAS',
    'CATEGORÍAS': 'CATEGORÍAS',
    'Comunidad': 'Comunidad',
    'vendidos': 'vendidos',
    'nuestra': 'nuestra',
    'internacional': 'internacional',
    'Fórmulas probadas': 'Fórmulas probadas',
    'entregan': 'entregan',
    'resultados': 'resultados',
    'visibles': 'visibles',
    'Vive': 'Vive',
    'belleza coreana': 'belleza coreana',
    'más allá': 'más allá',
    'productos': 'productos',
    'SABER': 'SABER',
    'MÁS': 'MÁS',
    'Tratamientos': 'Tratamientos',
    'Específicos': 'Específicos',
    'necesidad': 'necesidad',
    'Encuentra': 'Encuentra',
    'ideal': 'ideal',
    'tipo': 'tipo',
    'piel': 'piel',
    'estilo': 'estilo',
    'vida': 'vida',
    'Únete': 'Únete',
    'comunidad': 'comunidad',
    'Tips': 'Tips',
    'rutinas': 'rutinas',
    'lanzamientos': 'lanzamientos',
    'mucho más': 'mucho más',
    'Instagram': 'Instagram',
    'SEGUIR': 'SEGUIR',
    'EN': 'EN',
    'INSTAGRAM': 'INSTAGRAM',
    'seguros': 'seguros',
    'Fórmulas': 'Fórmulas',
    'efectivas': 'efectivas',
    'Resultados': 'Resultados',
    'reales': 'reales',
    'Inspirado': 'Inspirado',
    'Cruelty': 'Cruelty',
    'Free': 'Free',
    'CHEOTNUN CLUB': 'CHEOTNUN CLUB',
    'Sé': 'Sé',
    'primera': 'primera',
    'descubrir': 'descubrir',
    'nuevos': 'nuevos',
    'ofertas': 'ofertas',
    'correo': 'correo',
    'electrónico': 'electrónico',
    'éxito': 'éxito',
    'Bienvenido': 'Bienvenido',
    'Club': 'Club',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electrónico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte información relevante sobre tus compras. Tus datos están seguros y nunca se comparten sin tu consentimiento.': 'Al registrarte en Cheotnun, tus datos (nombre, correo electrónico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte información relevante sobre tus compras. Tus datos están seguros y nunca se comparten sin tu consentimiento.',
    // Corrigir.txt - Order status texts
    'Aguardando Confirmação da Loja': 'Aguardando Confirmación de la Tienda',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de até 48 horas úteis (até 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Você receberá uma notificação assim que o pedido estiver sendo preparado para envio.': 'Su pedido fue recibido y el pago fue confirmado. Estamos dentro del plazo operativo de hasta 48 horas hábiles (72 horas en feriados coreanos) para preparar y enviar su producto. Recibirá una notificación cuando el pedido esté siendo preparado para envío.',
  },
  pt: {
    // Header
    'Belleza que nace de la tradición. Cosmética que transforma.': 'Beleza que nasce da tradição. Cosmética que transforma.',
    'Envíos para toda América Latina': 'Envios para toda América Latina',
    'Atención': 'Atendimento',
    'Inicio': 'Início',
    'Tienda': 'Loja',
    'Rutinas': 'Rotinas',
    'Blog': 'Blog',
    'Experiencias': 'Experiências',
    'Buscar...': 'Buscar...',
    'Entrar': 'Entrar',
    'Crear Cuenta': 'Criar Conta',
    'Mi Panel': 'Meu Painel',
    'Cerrar Sesión': 'Sair',
    'Categorías': 'Categorias',
    'Productos': 'Produtos',
    'Sesión': 'Sessão',
    'Español': 'Espanhol',
    'Portugués': 'Português',
    'Inglés': 'Inglês',
    // Footer
    'Todos los derechos reservados': 'Todos os direitos reservados',
    'Orgulhosamente desenvolvido por': 'Orgulhosamente desenvolvido por',
    'En colaboración con': 'Em colaboração com',
    // Home
    'Tu belleza.': 'Sua beleza.',
    'Tu ritual.': 'Seu ritual.',
    'Tu momento.': 'Seu momento.',
    'CHEOTNUN — Tu tienda online de cosmética coreana K-Beauty': 'CHEOTNUN — Sua loja online de cosmética coreana K-Beauty',
    'Cheotnun es tu tienda online de cosmética coreana K-Beauty. Compra productos auténticos, descubre rutinas personalizadas para tu tipo de piel y recibe envíos a toda América Latina.': 'Cheotnun é sua loja online de cosmética coreana K-Beauty. Compre produtos autênticos, descubra rotinas personalizadas para seu tipo de pele e receba entregas em toda a América Latina.',
    'COMPRAR AHORA': 'COMPRAR AGORA',
    'DESCUBRIR RUTINAS': 'DESCOBRIR ROTINAS',
    'Colección Curada': 'Coleção Curada',
    'Descubre lo mejor del K-Beauty': 'Descubra o melhor do K-Beauty',
    'Productos auténticos para realzar tu belleza natural.': 'Produtos autênticos para realçar sua beleza natural.',
    'VER TODAS LAS CATEGORÍAS': 'VER TODAS AS CATEGORIAS',
    'Favoritos de la Comunidad': 'Favoritos da Comunidade',
    'Más vendidos': 'Mais vendidos',
    'Los favoritos de nuestra comunidad internacional. Fórmulas probadas que entregan resultados visibles.': 'Os favoritos da nossa comunidade internacional. Fórmulas testadas que entregam resultados visíveis.',
    'VER TODOS': 'VER TODOS',
    'Experiencias Cheotnun': 'Experiências Cheotnun',
    'Vive la belleza coreana más allá de los productos': 'Viva a beleza coreana além dos produtos',
    'SABER MÁS': 'SAIBA MAIS',
    'Tratamientos Específicos': 'Tratamentos Específicos',
    'Rutinas para cada necesidad': 'Rotinas para cada necessidade',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Encontre a rotina ideal para seu tipo de pele e estilo de vida.',
    'VER TODAS LAS RUTINAS': 'VER TODAS AS ROTINAS',
    'Únete a nuestra comunidad': 'Junte-se à nossa comunidade',
    'Tips, rutinas, lanzamientos y mucho más en Instagram.': 'Dicas, rotinas, lançamentos e muito mais no Instagram.',
    'SEGUIR EN INSTAGRAM': 'SEGUIR NO INSTAGRAM',
    'Ingredientes seguros': 'Ingredientes seguros',
    'Fórmulas efectivas': 'Fórmulas eficazes',
    'Resultados reales': 'Resultados reais',
    'Inspirado en la tradición': 'Inspirado na tradição',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'Suscríbete y recibe un 10% de descuento': 'Inscreva-se e receba 10% de desconto',
    'Tu correo electrónico': 'Seu e-mail',
    'SUSCRIBIRSE': 'INSCREVER-SE',
    '✓ ¡Te has suscrito con éxito! Bienvenido al Cheotnun Club.': '✓ Inscrição realizada com sucesso! Bem-vindo ao Cheotnun Club.',
    // Tienda
    'Tienda Cheotnun': 'Loja Cheotnun',
    'Todos los Productos': 'Todos os Produtos',
    'Filtrar': 'Filtrar',
    'Ordenar': 'Ordenar',
    'Más Recientes': 'Mais Recentes',
    'Menor Precio': 'Menor Preço',
    'Mayor Precio': 'Maior Preço',
    'Más Vendidos': 'Mais Vendidos',
    'Agregar al Carrito': 'Adicionar ao Carrinho',
    'Ver Detalles': 'Ver Detalhes',
    'Sin stock': 'Sem estoque',
    'Categoría': 'Categoria',
    'Marca': 'Marca',
    'Precio': 'Preço',
    'Buscar productos...': 'Buscar produtos...',
    'No hay productos': 'Não há produtos',
    'Tu carrito está vacío': 'Seu carrinho está vazio',
    'Ir a la Tienda': 'Ir à Loja',
    'Carrito': 'Carrinho',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Finalizar Compra',
    'Continuar Comprando': 'Continuar Comprando',
    'Eliminar': 'Excluir',
    'Cantidad': 'Quantidade',
    'Total': 'Total',
    'Envío calculado en el checkout': 'Frete calculado no checkout',
    // Rutinas
    'Rutinas de Skincare': 'Rotinas de Skincare',
    'Rutina de': 'Rotina de',
    'Productos para': 'Produtos para',
    'Ver Productos': 'Ver Produtos',
    // Blog
    'Blog Cheotnun K-Beauty': 'Blog Cheotnun K-Beauty',
    'Últimos Artículos': 'Últimos Artigos',
    'Leer más': 'Ler mais',
    'Publicado en': 'Publicado em',
    'Por': 'Por',
    'Volver al Blog': 'Voltar ao Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'EXPERIÊNCIA CHEOTNUN',
    'EN COLABORACIÓN CON MAEUM': 'EM COLABORAÇÃO COM MAEUM',
    'BEAUTY & CULTURA': 'BELEZA & CULTURA',
    'EXPLORAR VIAJES': 'EXPLORAR VIAGENS',
    'VER EXPERIENCIAS': 'VER EXPERIÊNCIAS',
    'Experiencias Exclusivas K-Beauty': 'Experiências Exclusivas K-Beauty',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Descubra a verdadeira arte do skincare coreano',
    'EXPLORAR EL CATÁLOGO': 'EXPLORAR O CATÁLOGO',
    'Inmersión y Bienestar': 'Imersão e Bem-estar',
    'Más allá del Producto:': 'Além do Produto:',
    'Una Filosofía de Cuidado': 'Uma Filosofia de Cuidado',
    'Programas de Inmersión Seleccionados': 'Programas de Imersão Selecionados',
    'Reservar Plaza': 'Reservar Vaga',
    'Inversión': 'Investimento',
    '¿Por qué elegirnos?': 'Por que nos escolher?',
    'Beneficios de la Inmersión Cheotnun': 'Benefícios da Imersão Cheotnun',
    'Certificación Premium': 'Certificação Premium',
    'Inmersión Cultural': 'Imersão Cultural',
    'Asesoría de por vida': 'Assessoria vitalícia',
    'Cómo participar del programa': 'Como participar do programa',
    'Paso a Paso': 'Passo a Passo',
    'Selecciona tu Experiencia': 'Selecione sua Experiência',
    'Reserva & Cuestionario': 'Reserva & Questionário',
    'Asesoría Individual': 'Assessoria Individual',
    'Vive la Experiencia': 'Viva a Experiência',
    '¿Dudas?': 'Dúvidas?',
    '¿Quieres una Experiencia Privada?': 'Quer uma Experiência Privada?',
    'HABLAR CON CONSULTORA': 'FALAR COM CONSULTORA',
    'Recibe invitaciones a nuevos talleres': 'Receba convites para novos workshops',
    // Dashboard
    'Mi Cuenta': 'Minha Conta',
    'Mis Pedidos': 'Meus Pedidos',
    'Mis Favoritos': 'Meus Favoritos',
    'Mis Datos': 'Meus Dados',
    'Direcciones': 'Endereços',
    'Club Cheotnun': 'Clube Cheotnun',
    'Configuración': 'Configurações',
    'Bienvenido/a': 'Bem-vindo/a',
    'Email': 'E-mail',
    'Teléfono': 'Telefone',
    'Actualizar Datos': 'Atualizar Dados',
    'Guardar': 'Salvar',
    'Cancelar': 'Cancelar',
    'Nombre': 'Nome',
    'Apellido': 'Sobrenome',
    'Fecha de Nacimiento': 'Data de Nascimento',
    'Género': 'Gênero',
    'Femenino': 'Feminino',
    'Masculino': 'Masculino',
    'Otro': 'Outro',
    // Auth
    '¿Olvidaste tu contraseña?': 'Esqueceu sua senha?',
    'Recuperar Contraseña': 'Recuperar Senha',
    'Ingresa tu email': 'Digite seu e-mail',
    'Enviar': 'Enviar',
    'Volver al Login': 'Voltar ao Login',
    'Crear tu cuenta': 'Criar sua conta',
    'Registrarme': 'Cadastrar',
    'Ya tengo cuenta': 'Já tenho conta',
    'Al menos 6 caracteres': 'Pelo menos 6 caracteres',
    'Confirmar contraseña': 'Confirmar senha',
    'He leído y acepto los': 'Li e aceito os',
    'Términos y Condiciones': 'Termos e Condições',
    'Política de Privacidad': 'Política de Privacidade',
    // Erros e Sucesso
    'Error': 'Erro',
    'Éxito': 'Sucesso',
    'Cargando...': 'Carregando...',
    'Producto agregado al carrito': 'Produto adicionado ao carrinho',
    'Producto eliminado del carrito': 'Produto removido do carrinho',
    'Producto agregado a favoritos': 'Produto adicionado aos favoritos',
    'Producto eliminado de favoritos': 'Produto removido dos favoritos',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electrónico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte información relevante sobre tus compras. Tus datos están seguros y nunca se comparten sin tu consentimiento.': 'Ao se registrar na Cheotnun, seus dados (nome, e-mail) são usados para processar seus pedidos, personalizar sua experiência de compra e enviar informações relevantes sobre suas compras. Seus dados estão seguros e nunca são compartilhados sem seu consentimento.',
    // Corrigir.txt - Order status texts
    'Aguardando Confirmação da Loja': 'Aguardando Confirmação da Loja',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de até 48 horas úteis (até 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Você receberá uma notificação assim que o pedido estiver sendo preparado para envio.': 'Seu pedido foi recebido e o pagamento foi confirmado. Estamos dentro do prazo operacional de até 48 horas úteis (72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Você receberá uma notificação assim que o pedido estiver sendo preparado para envio.',
  },
  en: {
    // Header
    'Belleza que nace de la tradición. Cosmética que transforma.': 'Beauty born from tradition. Cosmetics that transform.',
    'Envíos para toda América Latina': 'Shipping throughout Latin America',
    'Atención': 'Support',
    'Inicio': 'Home',
    'Tienda': 'Shop',
    'Rutinas': 'Routines',
    'Blog': 'Blog',
    'Experiencias': 'Experiences',
    'Buscar...': 'Search...',
    'Entrar': 'Log In',
    'Crear Cuenta': 'Create Account',
    'Mi Panel': 'My Dashboard',
    'Cerrar Sesión': 'Log Out',
    'Categorías': 'Categories',
    'Productos': 'Products',
    'Sesión': 'Session',
    'Español': 'Spanish',
    'Portugués': 'Portuguese',
    'Inglés': 'English',
    // Footer
    'Todos los derechos reservados': 'All rights reserved',
    'Orgulhosamente desenvolvido por': 'Proudly developed by',
    'En colaboración con': 'In collaboration with',
    // Home
    'Tu belleza.': 'Your beauty.',
    'Tu ritual.': 'Your ritual.',
    'Tu momento.': 'Your moment.',
    'CHEOTNUN — Tu tienda online de cosmética coreana K-Beauty': 'CHEOTNUN — Your online K-Beauty store',
    'Cheotnun es tu tienda online de cosmética coreana K-Beauty. Compra productos auténticos, descubre rutinas personalizadas para tu tipo de piel y recibe envíos a toda América Latina.': 'Cheotnun is your online K-Beauty store. Buy authentic Korean cosmetics, discover personalized skincare routines, and get delivery throughout Latin America.',
    'COMPRAR AHORA': 'SHOP NOW',
    'DESCUBRIR RUTINAS': 'DISCOVER ROUTINES',
    'Colección Curada': 'Curated Collection',
    'Descubre lo mejor del K-Beauty': 'Discover the best of K-Beauty',
    'Productos auténticos para realzar tu belleza natural.': 'Authentic products to enhance your natural beauty.',
    'VER TODAS LAS CATEGORÍAS': 'VIEW ALL CATEGORIES',
    'Favoritos de la Comunidad': 'Community Favorites',
    'Más vendidos': 'Best Sellers',
    'Los favoritos de nuestra comunidad internacional. Fórmulas probadas que entregan resultados visibles.': 'The favorites of our international community. Proven formulas that deliver visible results.',
    'VER TODOS': 'VIEW ALL',
    'Experiencias Cheotnun': 'Cheotnun Experiences',
    'Vive la belleza coreana más allá de los productos': 'Experience Korean beauty beyond products',
    'SABER MÁS': 'LEARN MORE',
    'Tratamientos Específicos': 'Specific Treatments',
    'Rutinas para cada necesidad': 'Routines for every need',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Find the ideal routine for your skin type and lifestyle.',
    'VER TODAS LAS RUTINAS': 'VIEW ALL ROUTINES',
    'Únete a nuestra comunidad': 'Join our community',
    'Tips, rutinas, lanzamientos y mucho más en Instagram.': 'Tips, routines, launches and much more on Instagram.',
    'SEGUIR EN INSTAGRAM': 'FOLLOW ON INSTAGRAM',
    'Ingredientes seguros': 'Safe Ingredients',
    'Fórmulas efectivas': 'Effective Formulas',
    'Resultados reales': 'Real Results',
    'Inspirado en la tradición': 'Inspired by tradition',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'Suscríbete y recibe un 10% de descuento': 'Subscribe and get 10% off',
    'Tu correo electrónico': 'Your email',
    'SUSCRIBIRSE': 'SUBSCRIBE',
    '✓ ¡Te has suscrito con éxito! Bienvenido al Cheotnun Club.': '✓ Successfully subscribed! Welcome to the Cheotnun Club.',
    // Tienda
    'Tienda Cheotnun': 'Cheotnun Shop',
    'Todos los Productos': 'All Products',
    'Filtrar': 'Filter',
    'Ordenar': 'Sort',
    'Más Recientes': 'Most Recent',
    'Menor Precio': 'Lowest Price',
    'Mayor Precio': 'Highest Price',
    'Más Vendidos': 'Best Sellers',
    'Agregar al Carrito': 'Add to Cart',
    'Ver Detalles': 'View Details',
    'Sin stock': 'Out of Stock',
    'Categoría': 'Category',
    'Marca': 'Brand',
    'Precio': 'Price',
    'Buscar productos...': 'Search products...',
    'No hay productos': 'No products',
    'Tu carrito está vacío': 'Your cart is empty',
    'Ir a la Tienda': 'Go to Shop',
    'Carrito': 'Cart',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Checkout',
    'Continuar Comprando': 'Continue Shopping',
    'Eliminar': 'Remove',
    'Cantidad': 'Quantity',
    'Total': 'Total',
    'Envío calculado en el checkout': 'Shipping calculated at checkout',
    // Rutinas
    'Rutinas de Skincare': 'Skincare Routines',
    'Rutina de': 'Routine for',
    'Productos para': 'Products for',
    'Ver Productos': 'View Products',
    // Blog
    'Blog Cheotnun K-Beauty': 'Cheotnun K-Beauty Blog',
    'Últimos Artículos': 'Latest Articles',
    'Leer más': 'Read more',
    'Publicado en': 'Published on',
    'Por': 'By',
    'Volver al Blog': 'Back to Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'CHEOTNUN EXPERIENCE',
    'EN COLABORACIÓN CON MAEUM': 'IN COLLABORATION WITH MAEUM',
    'BEAUTY & CULTURA': 'BEAUTY & CULTURE',
    'EXPLORAR VIAJES': 'EXPLORE TRAVEL',
    'VER EXPERIENCIAS': 'VIEW EXPERIENCES',
    'Experiencias Exclusivas K-Beauty': 'Exclusive K-Beauty Experiences',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Discover the true art of Korean skincare',
    'EXPLORAR EL CATÁLOGO': 'EXPLORE THE CATALOG',
    'Inmersión y Bienestar': 'Immersion & Wellness',
    'Más allá del Producto:': 'Beyond the Product:',
    'Una Filosofía de Cuidado': 'A Care Philosophy',
    'Programas de Inmersión Seleccionados': 'Selected Immersion Programs',
    'Reservar Plaza': 'Reserve Spot',
    'Inversión': 'Investment',
    '¿Por qué elegirnos?': 'Why choose us?',
    'Beneficios de la Inmersión Cheotnun': 'Benefits of Cheotnun Immersion',
    'Certificación Premium': 'Premium Certification',
    'Inmersión Cultural': 'Cultural Immersion',
    'Asesoría de por vida': 'Lifetime Consultation',
    'Cómo participar del programa': 'How to participate in the program',
    'Paso a Paso': 'Step by Step',
    'Selecciona tu Experiencia': 'Select Your Experience',
    'Reserva & Cuestionario': 'Reservation & Questionnaire',
    'Asesoría Individual': 'Individual Consultation',
    'Vive la Experiencia': 'Live the Experience',
    '¿Dudas?': 'Questions?',
    '¿Quieres una Experiencia Privada?': 'Want a Private Experience?',
    'HABLAR CON CONSULTORA': 'TALK TO CONSULTANT',
    'Recibe invitaciones a nuevos talleres': 'Receive invitations to new workshops',
    // Dashboard
    'Mi Cuenta': 'My Account',
    'Mis Pedidos': 'My Orders',
    'Mis Favoritos': 'My Favorites',
    'Mis Datos': 'My Data',
    'Direcciones': 'Addresses',
    'Club Cheotnun': 'Cheotnun Club',
    'Configuración': 'Settings',
    'Bienvenido/a': 'Welcome',
    'Email': 'Email',
    'Teléfono': 'Phone',
    'Actualizar Datos': 'Update Data',
    'Guardar': 'Save',
    'Cancelar': 'Cancel',
    'Nombre': 'Name',
    'Apellido': 'Surname',
    'Fecha de Nacimiento': 'Date of Birth',
    'Género': 'Gender',
    'Femenino': 'Female',
    'Masculino': 'Male',
    'Otro': 'Other',
    // Auth
    '¿Olvidaste tu contraseña?': 'Forgot your password?',
    'Recuperar Contraseña': 'Recover Password',
    'Ingresa tu email': 'Enter your email',
    'Enviar': 'Send',
    'Volver al Login': 'Back to Login',
    'Crear tu cuenta': 'Create your account',
    'Registrarme': 'Register',
    'Ya tengo cuenta': 'I already have an account',
    'Al menos 6 caracteres': 'At least 6 characters',
    'Confirmar contraseña': 'Confirm password',
    'He leído y acepto los': 'I have read and accept the',
    'Términos y Condiciones': 'Terms and Conditions',
    'Política de Privacidad': 'Privacy Policy',
    // Erros e Sucesso
    'Error': 'Error',
    'Éxito': 'Success',
    'Cargando...': 'Loading...',
    'Producto agregado al carrito': 'Product added to cart',
    'Producto eliminado del carrito': 'Product removed from cart',
    'Producto agregado a favoritos': 'Product added to favorites',
    'Producto eliminado de favoritos': 'Product removed from favorites',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electrónico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte información relevante sobre tus compras. Tus datos están seguros y nunca se comparten sin tu consentimiento.': 'When you register at Cheotnun, your data (name, email) is used to process your orders, personalize your shopping experience, and send you relevant information about your purchases. Your data is safe and never shared without your consent.',
    // Corrigir.txt - Order status texts
    'Aguardando Confirmação da Loja': 'Awaiting Store Confirmation',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de até 48 horas úteis (até 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Você receberá uma notificação assim que o pedido estiver sendo preparado para envio.': 'Your order has been received and payment confirmed. We are within the operational period of up to 48 business hours (72 hours on Korean holidays) to pick, prepare and ship your product. You will receive a notification as soon as your order is being prepared for shipping.',
  },
}

interface LanguageContextType {
  locale: Language
  setLocale: (l: Language) => void
  t: (key: string) => string
  isModalOpen: boolean
  setIsModalOpen: (open: boolean) => void
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Language>('es')
  const [isModalOpen, setIsModalOpen] = useState(false)

  useEffect(() => {
    const stored = localStorage.getItem('cheotnun_locale') as Language | null
    if (stored === 'es' || stored === 'pt' || stored === 'en') {
      setLocaleState(stored)
    }
  }, [])

  const setLocale = (l: Language) => {
    setLocaleState(l)
    localStorage.setItem('cheotnun_locale', l)
    document.cookie = `cheotnun_locale=${l};path=/;max-age=31536000;SameSite=Lax`
    setIsModalOpen(false)
  }

  const t = (key: string): string => {
    // Primeiro tenta nas traduções principais
    if (translations[locale]?.[key]) {
      return translations[locale][key]
    }
    // Depois tenta nas traduções adicionais
    if (locale !== 'es' && (additionalTranslations as any)[locale]?.[key]) {
      return (additionalTranslations as any)[locale][key]
    }
    // Retorna a chave original se não encontrar
    return key
  }

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, isModalOpen, setIsModalOpen }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}