'use client'

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'
import { additionalTranslations } from './translations'

type Language = 'es' | 'pt' | 'en'

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    'Belleza que nace de la tradiciÃ³n. CosmÃ©tica que transforma.': 'Belleza que nace de la tradiciÃ³n. CosmÃ©tica que transforma.',
    'EnvÃ­os para toda AmÃ©rica Latina': 'EnvÃ­os para toda AmÃ©rica Latina',
    'AtenciÃ³n': 'AtenciÃ³n',
    'Inicio': 'Inicio',
    'Tienda': 'Tienda',
    'Rutinas': 'Rutinas',
    'Blog': 'Blog',
    'Experiencias': 'Experiencias',
    'Buscar...': 'Buscar...',
    'Entrar': 'Iniciar SesiÃ³n',
    'Crear Cuenta': 'Crear Cuenta',
    'Mi Panel': 'Mi Panel',
    'Cerrar SesiÃ³n': 'Cerrar SesiÃ³n',
    'CategorÃ­as': 'CategorÃ­as',
    'Productos': 'Productos',
    'SesiÃ³n': 'SesiÃ³n',
    'EspaÃ±ol': 'EspaÃ±ol',
    'PortuguÃ©s': 'PortuguÃ©s',
    'InglÃ©s': 'InglÃ©s',
    'PolÃ­tica de Cookies': 'PolÃ­tica de Cookies',
    // Footer
    'Todos los derechos reservados': 'Todos los derechos reservados',
    'Orgulhosamente desenvolvido por': 'Desarrollado orgullosamente por',
    'En colaboraciÃ³n con': 'En colaboraciÃ³n con',
    // Home
    'Tu belleza.': 'Tu belleza.',
    'Tu ritual.': 'Tu ritual.',
    'Tu momento.': 'Tu momento.',
    'CHEOTNUN â€” Tu tienda online de cosmÃ©tica coreana K-Beauty': 'CHEOTNUN â€” Tu tienda online de cosmÃ©tica coreana K-Beauty',
    'Cheotnun es tu tienda online de cosmÃ©tica coreana K-Beauty. Compra productos autÃ©nticos, descubre rutinas personalizadas para tu tipo de piel y recibe envÃ­os a toda AmÃ©rica Latina.': 'Cheotnun es tu tienda online de cosmÃ©tica coreana K-Beauty. Compra productos autÃ©nticos, descubre rutinas personalizadas para tu tipo de piel y recibe envÃ­os a toda AmÃ©rica Latina.',
    'COMPRAR AHORA': 'COMPRAR AHORA',
    'DESCUBRIR RUTINAS': 'DESCUBRIR RUTINAS',
    'ColecciÃ³n Curada': 'ColecciÃ³n Curada',
    'Descubre lo mejor del K-Beauty': 'Descubre lo mejor del K-Beauty',
    'Productos autÃ©nticos para realzar tu belleza natural.': 'Productos autÃ©nticos para realzar tu belleza natural.',
    'VER TODAS LAS CATEGORÃAS': 'VER TODAS LAS CATEGORÃAS',
    'Favoritos de la Comunidad': 'Favoritos de la Comunidad',
    'MÃ¡s vendidos': 'MÃ¡s vendidos',
    'Los favoritos de nuestra comunidad internacional. FÃ³rmulas probadas que entregan resultados visibles.': 'Los favoritos de nuestra comunidad internacional. FÃ³rmulas probadas que entregan resultados visibles.',
    'VER TODOS': 'VER TODOS',
    'Experiencias Cheotnun': 'Experiencias Cheotnun',
    'Vive la belleza coreana mÃ¡s allÃ¡ de los productos': 'Vive la belleza coreana mÃ¡s allÃ¡ de los productos',
    'SABER MÃS': 'SABER MÃS',
    'Tratamientos EspecÃ­ficos': 'Tratamientos EspecÃ­ficos',
    'Rutinas para cada necesidad': 'Rutinas para cada necesidad',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.',
    'VER TODAS LAS RUTINAS': 'VER TODAS LAS RUTINAS',
    'Ãšnete a nuestra comunidad': 'Ãšnete a nuestra comunidad',
    'Tips, rutinas, lanzamientos y mucho mÃ¡s en Instagram.': 'Tips, rutinas, lanzamientos y mucho mÃ¡s en Instagram.',
    'SEGUIR EN INSTAGRAM': 'SEGUIR EN INSTAGRAM',
    'Ingredientes seguros': 'Ingredientes seguros',
    'FÃ³rmulas efectivas': 'FÃ³rmulas efectivas',
    'Resultados reales': 'Resultados reales',
    'Inspirado en la tradiciÃ³n': 'Inspirado en la tradiciÃ³n',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'SuscrÃ­bete y recibe un 10% de descuento': 'SuscrÃ­bete y recibe un 10% de descuento',
    'Tu correo electrÃ³nico': 'Tu correo electrÃ³nico',
    'SUSCRIBIRSE': 'SUSCRIBIRSE',
    'âœ“ Â¡Te has suscrito con Ã©xito! Bienvenido al Cheotnun Club.': 'âœ“ Â¡Te has suscrito con Ã©xito! Bienvenido al Cheotnun Club.',
    // Tienda
    'Tienda Cheotnun': 'Tienda Cheotnun',
    'Todos los Productos': 'Todos los Productos',
    'Filtrar': 'Filtrar',
    'Ordenar': 'Ordenar',
    'MÃ¡s Recientes': 'MÃ¡s Recientes',
    'Menor Precio': 'Menor Precio',
    'Mayor Precio': 'Mayor Precio',
    'MÃ¡s Vendidos': 'MÃ¡s Vendidos',
    'Agregar al Carrito': 'Agregar al Carrito',
    'Ver Detalles': 'Ver Detalles',
    'Sin stock': 'Sin Stock',
    'CategorÃ­a': 'CategorÃ­a',
    'Marca': 'Marca',
    'Precio': 'Precio',
    'Buscar productos...': 'Buscar productos...',
    'No hay productos': 'No hay productos',
    'Tu carrito estÃ¡ vacÃ­o': 'Tu carrito estÃ¡ vacÃ­o',
    'Ir a la Tienda': 'Ir a la Tienda',
    'Carrito': 'Carrito',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Finalizar Compra',
    'Continuar Comprando': 'Continuar Comprando',
    'Eliminar': 'Eliminar',
    'Cantidad': 'Cantidad',
    'Total': 'Total',
    'EnvÃ­o calculado en el checkout': 'EnvÃ­o calculado en el checkout',
    // Rutinas
    'Rutinas de Skincare': 'Rutinas de Skincare',
    'Rutina de': 'Rutina de',
    'Productos para': 'Productos para',
    'Ver Productos': 'Ver Productos',
    // Blog
    'Blog Cheotnun K-Beauty': 'Blog Cheotnun K-Beauty',
    'Ãšltimos ArtÃ­culos': 'Ãšltimos ArtÃ­culos',
    'Leer mÃ¡s': 'Leer mÃ¡s',
    'Publicado en': 'Publicado en',
    'Por': 'Por',
    'Volver al Blog': 'Volver al Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'CHEOTNUN EXPERIENCE',
    'EN COLABORACIÃ“N CON MAEUM': 'EN COLABORACIÃ“N CON MAEUM',
    'BEAUTY & CULTURA': 'BEAUTY & CULTURA',
    'EXPLORAR VIAJES': 'EXPLORAR VIAJES',
    'VER EXPERIENCIAS': 'VER EXPERIENCIAS',
    'Experiencias Exclusivas K-Beauty': 'Experiencias Exclusivas K-Beauty',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Descubre el verdadero arte del skincare coreano',
    'EXPLORAR EL CATÃLOGO': 'EXPLORAR EL CATÃLOGO',
    'InmersiÃ³n y Bienestar': 'InmersiÃ³n y Bienestar',
    'MÃ¡s allÃ¡ del Producto:': 'MÃ¡s allÃ¡ del Producto:',
    'Una FilosofÃ­a de Cuidado': 'Una FilosofÃ­a de Cuidado',
    'Programas de InmersiÃ³n Seleccionados': 'Programas de InmersiÃ³n Seleccionados',
    'Reservar Plaza': 'Reservar Plaza',
    'InversiÃ³n': 'InversiÃ³n',
    'Â¿Por quÃ© elegirnos?': 'Â¿Por quÃ© elegirnos?',
    'Beneficios de la InmersiÃ³n Cheotnun': 'Beneficios de la InmersiÃ³n Cheotnun',
    'CertificaciÃ³n Premium': 'CertificaciÃ³n Premium',
    'InmersiÃ³n Cultural': 'InmersiÃ³n Cultural',
    'AsesorÃ­a de por vida': 'AsesorÃ­a de por vida',
    'CÃ³mo participar del programa': 'CÃ³mo participar del programa',
    'Paso a Paso': 'Paso a Paso',
    'Selecciona tu Experiencia': 'Selecciona tu Experiencia',
    'Reserva & Cuestionario': 'Reserva & Cuestionario',
    'AsesorÃ­a Individual': 'AsesorÃ­a Individual',
    'Vive la Experiencia': 'Vive la Experiencia',
    'Â¿Dudas?': 'Â¿Dudas?',
    'Â¿Quieres una Experiencia Privada?': 'Â¿Quieres una Experiencia Privada?',
    'HABLAR CON CONSULTORA': 'HABLAR CON CONSULTORA',
    'Recibe invitaciones a nuevos talleres': 'Recibe invitaciones a nuevos talleres',
    // Dashboard
    'Mi Cuenta': 'Mi Cuenta',
    'Mis Pedidos': 'Mis Pedidos',
    'Mis Favoritos': 'Mis Favoritos',
    'Mis Datos': 'Mis Datos',
    'Direcciones': 'Direcciones',
    'Club Cheotnun': 'Club Cheotnun',
    'ConfiguraciÃ³n': 'ConfiguraciÃ³n',
    'Bienvenido/a': 'Bienvenido/a',
    'Email': 'Email',
    'TelÃ©fono': 'TelÃ©fono',
    'Actualizar Datos': 'Actualizar Datos',
    'Guardar': 'Guardar',
    'Cancelar': 'Cancelar',
    'Nombre': 'Nombre',
    'Apellido': 'Apellido',
    'Fecha de Nacimiento': 'Fecha de Nacimiento',
    'GÃ©nero': 'GÃ©nero',
    'Femenino': 'Femenino',
    'Masculino': 'Masculino',
    'Otro': 'Otro',
    // Auth
    'Â¿Olvidaste tu contraseÃ±a?': 'Â¿Olvidaste tu contraseÃ±a?',
    'Recuperar ContraseÃ±a': 'Recuperar ContraseÃ±a',
    'Ingresa tu email': 'Ingresa tu email',
    'Enviar': 'Enviar',
    'Volver al Login': 'Volver al Login',
    'Crear tu cuenta': 'Crear tu cuenta',
    'Registrarme': 'Registrarme',
    'Ya tengo cuenta': 'Ya tengo cuenta',
    'Al menos 6 caracteres': 'Al menos 6 caracteres',
    'Confirmar contraseÃ±a': 'Confirmar contraseÃ±a',
    'He leÃ­do y acepto los': 'He leÃ­do y acepto los',
    'TÃ©rminos y Condiciones': 'TÃ©rminos y Condiciones',
    'PolÃ­tica de Privacidad': 'PolÃ­tica de Privacidad',
    // Erros e Sucesso
    'Error': 'Error',
    'Ã‰xito': 'Ã‰xito',
    'Cargando...': 'Cargando...',
    'Producto agregado al carrito': 'Producto agregado al carrito',
    'Producto eliminado del carrito': 'Producto eliminado del carrito',
    'Producto agregado a favoritos': 'Producto agregado a favoritos',
    'Producto eliminado de favoritos': 'Producto eliminado de favoritos',
    // Tienda textos
    'agregado al carrito': 'agregado al carrito',
    'CatÃ¡logo de CosmÃ©ticos': 'CatÃ¡logo de CosmÃ©ticos',
    'Todas las categorÃ­as': 'Todas las categorÃ­as',
    'Todas las marcas': 'Todas las marcas',
    'Buscar Producto': 'Buscar Producto',
    'Buscar Produto': 'Buscar Producto',
    'Ej: SÃ©rum, Limpiador...': 'Ej: SÃ©rum, Limpiador...',
    'Marcas': 'Marcas',
    'Filtrar': 'Filtrar',
    'Filtrar por': 'Filtrar por',
    'produtos': 'productos',
    'Agotado': 'Agotado',
    'VER DETALLES': 'VER DETALLES',
    'CategorÃ­a Seleccionada': 'CategorÃ­a Seleccionada',
    'Limpiar filtro': 'Limpiar filtro',
    'NingÃºn producto coincide con los filtros aplicados.': 'NingÃºn producto coincide con los filtros aplicados.',
    'Ordenar por': 'Ordenar por',
    'Precio: Menor a Mayor': 'Precio: Menor a Mayor',
    'Precio: Mayor a Menor': 'Precio: Mayor a Menor',
    'MÃ¡s recientes': 'MÃ¡s recientes',
    'Nombre: A-Z': 'Nombre: A-Z',
    'Nombre: Z-A': 'Nombre: Z-A',
    'Sin resultados': 'Sin resultados',
    'No se encontraron productos': 'No se encontraron productos',
    'Intenta con otros filtros': 'Intenta con otros filtros',
    'Ver Producto': 'Ver Producto',
    'Producto': 'Producto',
    'Detalles': 'Detalles',
    'DescripciÃ³n': 'DescripciÃ³n',
    'InformaciÃ³n': 'InformaciÃ³n',
    'Ingredientes': 'Ingredientes',
    'Modo de uso': 'Modo de uso',
    'Beneficios': 'Beneficios',
    'CaracterÃ­sticas': 'CaracterÃ­sticas',
    'Opiniones': 'Opiniones',
    'ReseÃ±as': 'ReseÃ±as',
    'CalificaciÃ³n': 'CalificaciÃ³n',
    'Escribir opiniÃ³n': 'Escribir opiniÃ³n',
    'Enviar opiniÃ³n': 'Enviar opiniÃ³n',
    'Tu opiniÃ³n': 'Tu opiniÃ³n',
    'Opiniones de clientes': 'Opiniones de clientes',
    'Producto relacionado': 'Producto relacionado',
    'Productos relacionados': 'Productos relacionados',
    'Te puede interesar': 'Te puede interesar',
    'Ver todos': 'Ver todos',
    'Volver': 'Volver',
    'Anterior': 'Anterior',
    'Siguiente': 'Siguiente',
    'PÃ¡gina': 'PÃ¡gina',
    'de': 'de',
    // Header completo
    'Belleza que nace': 'Belleza que nace',
    'tradiciÃ³n': 'tradiciÃ³n',
    'CosmÃ©tica que transforma': 'CosmÃ©tica que transforma',
    'EnvÃ­os para toda': 'EnvÃ­os para toda',
    'AmÃ©rica Latina': 'AmÃ©rica Latina',
    'Buscar': 'Buscar',
    'Panel': 'Panel',
    'Salir': 'Salir',
    'Favoritos': 'Favoritos',
    'Ver carrito': 'Ver carrito',
    'Tu carrito': 'Tu carrito',
    'vacÃ­o': 'vacÃ­o',
    'Continuar': 'Continuar',
    'Comprar': 'Comprar',
    'Ofertas': 'Ofertas',
    'Novedades': 'Novedades',
    'Colecciones': 'Colecciones',
    'Sets': 'Sets',
    'Kits': 'Kits',
    'Regalos': 'Regalos',
    'Tarjeta Regalo': 'Tarjeta Regalo',
    'Ayuda': 'Ayuda',
    'EnvÃ­os': 'EnvÃ­os',
    'Devoluciones': 'Devoluciones',
    'FAQ': 'FAQ',
    'Contacto': 'Contacto',
    'Sobre Nosotros': 'Sobre Nosotros',
    'Nuestra Historia': 'Nuestra Historia',
    'Sostenibilidad': 'Sostenibilidad',
    'Skin Care': 'Skin Care',
    'Maquillaje': 'Maquillaje',
    'Cabello': 'Cabello',
    'Cuerpo': 'Cuerpo',
    'Solares': 'Solares',
    'Hombres': 'Hombres',
    'NiÃ±os': 'NiÃ±os',
    'Profesionales': 'Profesionales',
    'SalÃ³n': 'SalÃ³n',
    'Spa': 'Spa',
    // Banner Hero
    'Tu belleza': 'Tu belleza',
    'Tu ritual': 'Tu ritual',
    'Tu momento': 'Tu momento',
    'CosmÃ©ticos coreanos': 'CosmÃ©ticos coreanos',
    'autÃ©nticos': 'autÃ©nticos',
    'seleccionados': 'seleccionados',
    'cada etapa': 'cada etapa',
    'cuidado facial': 'cuidado facial',
    'FÃ³rmulas botÃ¡nicas': 'FÃ³rmulas botÃ¡nicas',
    'revelan': 'revelan',
    'luminosidad natural': 'luminosidad natural',
    'COMPRAR': 'COMPRAR',
    'AHORA': 'AHORA',
    'DESCUBRIR': 'DESCUBRIR',
    'RUTINAS': 'RUTINAS',
    // SeÃ§Ãµes Home
    'ColecciÃ³n': 'ColecciÃ³n',
    'Curada': 'Curada',
    'Descubre': 'Descubre',
    'mejor': 'mejor',
    'K-Beauty': 'K-Beauty',
    'realzar': 'realzar',
    'belleza natural': 'belleza natural',
    'VER': 'VER',
    'TODAS': 'TODAS',
    'LAS': 'LAS',
    'CATEGORÃAS': 'CATEGORÃAS',
    'Comunidad': 'Comunidad',
    'vendidos': 'vendidos',
    'nuestra': 'nuestra',
    'internacional': 'internacional',
    'FÃ³rmulas probadas': 'FÃ³rmulas probadas',
    'entregan': 'entregan',
    'resultados': 'resultados',
    'visibles': 'visibles',
    'Vive': 'Vive',
    'belleza coreana': 'belleza coreana',
    'mÃ¡s allÃ¡': 'mÃ¡s allÃ¡',
    'productos': 'productos',
    'SABER': 'SABER',
    'MÃS': 'MÃS',
    'Tratamientos': 'Tratamientos',
    'EspecÃ­ficos': 'EspecÃ­ficos',
    'necesidad': 'necesidad',
    'Encuentra': 'Encuentra',
    'ideal': 'ideal',
    'tipo': 'tipo',
    'piel': 'piel',
    'estilo': 'estilo',
    'vida': 'vida',
    'Ãšnete': 'Ãšnete',
    'comunidad': 'comunidad',
    'Tips': 'Tips',
    'rutinas': 'rutinas',
    'lanzamientos': 'lanzamientos',
    'mucho mÃ¡s': 'mucho mÃ¡s',
    'Instagram': 'Instagram',
    'SEGUIR': 'SEGUIR',
    'EN': 'EN',
    'INSTAGRAM': 'INSTAGRAM',
    'seguros': 'seguros',
    'FÃ³rmulas': 'FÃ³rmulas',
    'efectivas': 'efectivas',
    'Resultados': 'Resultados',
    'reales': 'reales',
    'Inspirado': 'Inspirado',
    'Cruelty': 'Cruelty',
    'Free': 'Free',
    'CHEOTNUN CLUB': 'CHEOTNUN CLUB',
    'SÃ©': 'SÃ©',
    'primera': 'primera',
    'descubrir': 'descubrir',
    'nuevos': 'nuevos',
    'ofertas': 'ofertas',
    'correo': 'correo',
    'electrÃ³nico': 'electrÃ³nico',
    'Ã©xito': 'Ã©xito',
    'Bienvenido': 'Bienvenido',
    'Club': 'Club',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electrÃ³nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaciÃ³n relevante sobre tus compras. Tus datos estÃ¡n seguros y nunca se comparten sin tu consentimiento.': 'Al registrarte en Cheotnun, tus datos (nombre, correo electrÃ³nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaciÃ³n relevante sobre tus compras. Tus datos estÃ¡n seguros y nunca se comparten sin tu consentimiento.',
    // Complete profile (Google OAuth)
    'Completa tu registro': 'Completa tu registro',
    'Solo falta completar tus datos para finalizar tu cuenta.': 'Solo falta completar tus datos para finalizar tu cuenta.',
    'Guardando...': 'Guardando...',
    'Completar Registro': 'Completar Registro',
    'âœ“ Registro completado!': 'âœ“ Registro completado!',
    'Erro ao salvar dados.': 'Error al guardar los datos.',
    // Recovery password
    'Nueva ContraseÃ±a': 'Nueva ContraseÃ±a',
    'Elige una nueva contraseÃ±a para tu cuenta.': 'Elige una nueva contraseÃ±a para tu cuenta.',
    'âœ“ ContraseÃ±a actualizada. Redireccionando...': 'âœ“ ContraseÃ±a actualizada. Redireccionando...',
    'Actualizando...': 'Actualizando...',
    'CAMBIAR CONTRASEÃ‘A': 'CAMBIAR CONTRASEÃ‘A',
    'Error al actualizar la contraseÃ±a.': 'Error al actualizar la contraseÃ±a.',
    // Corrigir.txt - Order status texts
    'Aguardando ConfirmaÃ§Ã£o da Loja': 'Aguardando ConfirmaciÃ³n de la Tienda',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de atÃ© 48 horas Ãºteis (atÃ© 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. VocÃª receberÃ¡ uma notificaÃ§Ã£o assim que o pedido estiver sendo preparado para envio.': 'Su pedido fue recibido y el pago fue confirmado. Estamos dentro del plazo operativo de hasta 48 horas hÃ¡biles (72 horas en feriados coreanos) para preparar y enviar su producto. RecibirÃ¡ una notificaciÃ³n cuando el pedido estÃ© siendo preparado para envÃ­o.',
  },
  pt: {
    // Header
    'Belleza que nace de la tradiciÃ³n. CosmÃ©tica que transforma.': 'Beleza que nasce da tradiÃ§Ã£o. CosmÃ©tica que transforma.',
    'EnvÃ­os para toda AmÃ©rica Latina': 'Envios para toda AmÃ©rica Latina',
    'AtenciÃ³n': 'Atendimento',
    'Inicio': 'InÃ­cio',
    'Tienda': 'Loja',
    'Rutinas': 'Rotinas',
    'Blog': 'Blog',
    'Experiencias': 'ExperiÃªncias',
    'Buscar...': 'Buscar...',
    'Entrar': 'Entrar',
    'Crear Cuenta': 'Criar Conta',
    'Mi Panel': 'Meu Painel',
    'Cerrar SesiÃ³n': 'Sair',
    'CategorÃ­as': 'Categorias',
    'Productos': 'Produtos',
    'SesiÃ³n': 'SessÃ£o',
    'EspaÃ±ol': 'Espanhol',
    'PortuguÃ©s': 'PortuguÃªs',
    'InglÃ©s': 'InglÃªs',
    // Footer
    'Todos los derechos reservados': 'Todos os direitos reservados',
    'Orgulhosamente desenvolvido por': 'Orgulhosamente desenvolvido por',
    'En colaboraciÃ³n con': 'Em colaboraÃ§Ã£o com',
    // Home
    'Tu belleza.': 'Sua beleza.',
    'Tu ritual.': 'Seu ritual.',
    'Tu momento.': 'Seu momento.',
    'CHEOTNUN â€” Tu tienda online de cosmÃ©tica coreana K-Beauty': 'CHEOTNUN â€” Sua loja online de cosmÃ©tica coreana K-Beauty',
    'Cheotnun es tu tienda online de cosmÃ©tica coreana K-Beauty. Compra productos autÃ©nticos, descubre rutinas personalizadas para tu tipo de piel y recibe envÃ­os a toda AmÃ©rica Latina.': 'Cheotnun Ã© sua loja online de cosmÃ©tica coreana K-Beauty. Compre produtos autÃªnticos, descubra rotinas personalizadas para seu tipo de pele e receba entregas em toda a AmÃ©rica Latina.',
    'COMPRAR AHORA': 'COMPRAR AGORA',
    'DESCUBRIR RUTINAS': 'DESCOBRIR ROTINAS',
    'ColecciÃ³n Curada': 'ColeÃ§Ã£o Curada',
    'Descubre lo mejor del K-Beauty': 'Descubra o melhor do K-Beauty',
    'Productos autÃ©nticos para realzar tu belleza natural.': 'Produtos autÃªnticos para realÃ§ar sua beleza natural.',
    'VER TODAS LAS CATEGORÃAS': 'VER TODAS AS CATEGORIAS',
    'Favoritos de la Comunidad': 'Favoritos da Comunidade',
    'MÃ¡s vendidos': 'Mais vendidos',
    'Los favoritos de nuestra comunidad internacional. FÃ³rmulas probadas que entregan resultados visibles.': 'Os favoritos da nossa comunidade internacional. FÃ³rmulas testadas que entregam resultados visÃ­veis.',
    'VER TODOS': 'VER TODOS',
    'Experiencias Cheotnun': 'ExperiÃªncias Cheotnun',
    'Vive la belleza coreana mÃ¡s allÃ¡ de los productos': 'Viva a beleza coreana alÃ©m dos produtos',
    'SABER MÃS': 'SAIBA MAIS',
    'Tratamientos EspecÃ­ficos': 'Tratamentos EspecÃ­ficos',
    'Rutinas para cada necesidad': 'Rotinas para cada necessidade',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Encontre a rotina ideal para seu tipo de pele e estilo de vida.',
    'VER TODAS LAS RUTINAS': 'VER TODAS AS ROTINAS',
    'Ãšnete a nuestra comunidad': 'Junte-se Ã  nossa comunidade',
    'Tips, rutinas, lanzamientos y mucho mÃ¡s en Instagram.': 'Dicas, rotinas, lanÃ§amentos e muito mais no Instagram.',
    'SEGUIR EN INSTAGRAM': 'SEGUIR NO INSTAGRAM',
    'Ingredientes seguros': 'Ingredientes seguros',
    'FÃ³rmulas efectivas': 'FÃ³rmulas eficazes',
    'Resultados reales': 'Resultados reais',
    'Inspirado en la tradiciÃ³n': 'Inspirado na tradiÃ§Ã£o',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'SuscrÃ­bete y recibe un 10% de descuento': 'Inscreva-se e receba 10% de desconto',
    'Tu correo electrÃ³nico': 'Seu e-mail',
    'SUSCRIBIRSE': 'INSCREVER-SE',
    'âœ“ Â¡Te has suscrito con Ã©xito! Bienvenido al Cheotnun Club.': 'âœ“ InscriÃ§Ã£o realizada com sucesso! Bem-vindo ao Cheotnun Club.',
    // Tienda textos - PT
    'agregado al carrito': 'adicionado ao carrinho',
    'CatÃ¡logo de CosmÃ©ticos': 'CatÃ¡logo de CosmÃ©ticos',
    'Todas las categorÃ­as': 'Todas as categorias',
    'Todas las marcas': 'Todas as marcas',
    'Buscar Producto': 'Buscar Produto',
    'Buscar Produto': 'Buscar Produto',
    'Ej: SÃ©rum, Limpiador...': 'Ex: SÃ©rum, Limpador...',
    'Marcas': 'Marcas',
    'Filtrar': 'Filtrar',
    'Filtrar por': 'Filtrar por',
    'produtos': 'produtos',
    'Agotado': 'Esgotado',
    'VER DETALLES': 'VER DETALHES',
    'CategorÃ­a Seleccionada': 'Categoria Selecionada',
    'Limpiar filtro': 'Limpar filtro',
    'NingÃºn producto coincide con los filtros aplicados.': 'Nenhum produto corresponde aos filtros aplicados.',
    'Todos los Productos': 'Todos os Produtos',
    'Ordenar': 'Ordenar',
    'MÃ¡s Recientes': 'Mais Recentes',
    'Menor Precio': 'Menor PreÃ§o',
    'Mayor Precio': 'Maior PreÃ§o',
    'MÃ¡s Vendidos': 'Mais Vendidos',
    'Agregar al Carrito': 'Adicionar ao Carrinho',
    'Ver Detalles': 'Ver Detalhes',
    'Sin stock': 'Sem estoque',
    'CategorÃ­a': 'Categoria',
    'Marca': 'Marca',
    'Precio': 'PreÃ§o',
    'Buscar productos...': 'Buscar produtos...',
    'No hay productos': 'NÃ£o hÃ¡ produtos',
    'Tu carrito estÃ¡ vacÃ­o': 'Seu carrinho estÃ¡ vazio',
    'Ir a la Tienda': 'Ir Ã  Loja',
    'Carrito': 'Carrinho',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Finalizar Compra',
    'Continuar Comprando': 'Continuar Comprando',
    'Eliminar': 'Excluir',
    'Cantidad': 'Quantidade',
    'Total': 'Total',
    'EnvÃ­o calculado en el checkout': 'Frete calculado no checkout',
    // Rutinas
    'Rutinas de Skincare': 'Rotinas de Skincare',
    'Rutina de': 'Rotina de',
    'Productos para': 'Produtos para',
    'Ver Productos': 'Ver Produtos',
    // Blog
    'Blog Cheotnun K-Beauty': 'Blog Cheotnun K-Beauty',
    'Ãšltimos ArtÃ­culos': 'Ãšltimos Artigos',
    'Leer mÃ¡s': 'Ler mais',
    'Publicado en': 'Publicado em',
    'Por': 'Por',
    'Volver al Blog': 'Voltar ao Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'EXPERIÃŠNCIA CHEOTNUN',
    'EN COLABORACIÃ“N CON MAEUM': 'EM COLABORAÃ‡ÃƒO COM MAEUM',
    'BEAUTY & CULTURA': 'BELEZA & CULTURA',
    'EXPLORAR VIAJES': 'EXPLORAR VIAGENS',
    'VER EXPERIENCIAS': 'VER EXPERIÃŠNCIAS',
    'Experiencias Exclusivas K-Beauty': 'ExperiÃªncias Exclusivas K-Beauty',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Descubra a verdadeira arte do skincare coreano',
    'EXPLORAR EL CATÃLOGO': 'EXPLORAR O CATÃLOGO',
    'InmersiÃ³n y Bienestar': 'ImersÃ£o e Bem-estar',
    'MÃ¡s allÃ¡ del Producto:': 'AlÃ©m do Produto:',
    'Una FilosofÃ­a de Cuidado': 'Uma Filosofia de Cuidado',
    'Programas de InmersiÃ³n Seleccionados': 'Programas de ImersÃ£o Selecionados',
    'Reservar Plaza': 'Reservar Vaga',
    'InversiÃ³n': 'Investimento',
    'Â¿Por quÃ© elegirnos?': 'Por que nos escolher?',
    'Beneficios de la InmersiÃ³n Cheotnun': 'BenefÃ­cios da ImersÃ£o Cheotnun',
    'CertificaciÃ³n Premium': 'CertificaÃ§Ã£o Premium',
    'InmersiÃ³n Cultural': 'ImersÃ£o Cultural',
    'AsesorÃ­a de por vida': 'Assessoria vitalÃ­cia',
    'CÃ³mo participar del programa': 'Como participar do programa',
    'Paso a Paso': 'Passo a Passo',
    'Selecciona tu Experiencia': 'Selecione sua ExperiÃªncia',
    'Reserva & Cuestionario': 'Reserva & QuestionÃ¡rio',
    'AsesorÃ­a Individual': 'Assessoria Individual',
    'Vive la Experiencia': 'Viva a ExperiÃªncia',
    'Â¿Dudas?': 'DÃºvidas?',
    'Â¿Quieres una Experiencia Privada?': 'Quer uma ExperiÃªncia Privada?',
    'HABLAR CON CONSULTORA': 'FALAR COM CONSULTORA',
    'Recibe invitaciones a nuevos talleres': 'Receba convites para novos workshops',
    // Dashboard
    'Mi Cuenta': 'Minha Conta',
    'Mis Pedidos': 'Meus Pedidos',
    'Mis Favoritos': 'Meus Favoritos',
    'Mis Datos': 'Meus Dados',
    'Direcciones': 'EndereÃ§os',
    'Club Cheotnun': 'Clube Cheotnun',
    'ConfiguraciÃ³n': 'ConfiguraÃ§Ãµes',
    'Bienvenido/a': 'Bem-vindo/a',
    'Email': 'E-mail',
    'TelÃ©fono': 'Telefone',
    'Actualizar Datos': 'Atualizar Dados',
    'Guardar': 'Salvar',
    'Cancelar': 'Cancelar',
    'Nombre': 'Nome',
    'Apellido': 'Sobrenome',
    'Fecha de Nacimiento': 'Data de Nascimento',
    'GÃ©nero': 'GÃªnero',
    'Femenino': 'Feminino',
    'Masculino': 'Masculino',
    'Otro': 'Outro',
    // Auth
    'Â¿Olvidaste tu contraseÃ±a?': 'Esqueceu sua senha?',
    'Recuperar ContraseÃ±a': 'Recuperar Senha',
    'Ingresa tu email': 'Digite seu e-mail',
    'Enviar': 'Enviar',
    'Volver al Login': 'Voltar ao Login',
    'Crear tu cuenta': 'Criar sua conta',
    'Registrarme': 'Cadastrar',
    'Ya tengo cuenta': 'JÃ¡ tenho conta',
    'Al menos 6 caracteres': 'Pelo menos 6 caracteres',
    'Confirmar contraseÃ±a': 'Confirmar senha',
    'He leÃ­do y acepto los': 'Li e aceito os',
    'TÃ©rminos y Condiciones': 'Termos e CondiÃ§Ãµes',
    'PolÃ­tica de Privacidad': 'PolÃ­tica de Privacidade',
    'PolÃ­tica de Cookies': 'PolÃ­tica de Cookies',
    // Erros e Sucesso
    'Error': 'Erro',
    'Ã‰xito': 'Sucesso',
    'Cargando...': 'Carregando...',
    'Producto agregado al carrito': 'Produto adicionado ao carrinho',
    'Producto eliminado del carrito': 'Produto removido do carrinho',
    'Producto agregado a favoritos': 'Produto adicionado aos favoritos',
    'Producto eliminado de favoritos': 'Produto removido dos favoritos',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electrÃ³nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaciÃ³n relevante sobre tus compras. Tus datos estÃ¡n seguros y nunca se comparten sin tu consentimiento.': 'Ao se registrar na Cheotnun, seus dados (nome, e-mail) sÃ£o usados para processar seus pedidos, personalizar sua experiÃªncia de compra e enviar informaÃ§Ãµes relevantes sobre suas compras. Seus dados estÃ£o seguros e nunca sÃ£o compartilhados sem seu consentimento.',
    // Complete profile (Google OAuth)
    'Completa tu registro': 'Complete seu cadastro',
    'Solo falta completar tus datos para finalizar tu cuenta.': 'SÃ³ falta completar seus dados para finalizar sua conta.',
    'Guardando...': 'Salvando...',
    'Completar Registro': 'Completar Cadastro',
    'âœ“ Registro completado!': 'âœ“ Cadastro concluÃ­do!',
    'Erro ao salvar dados.': 'Erro ao salvar dados.',
    // Recovery password
    'Nueva ContraseÃ±a': 'Nova Senha',
    'Elige una nueva contraseÃ±a para tu cuenta.': 'Escolha uma nova senha para sua conta.',
    'âœ“ ContraseÃ±a actualizada. Redireccionando...': 'âœ“ Senha atualizada. Redirecionando...',
    'Actualizando...': 'Atualizando...',
    'CAMBIAR CONTRASEÃ‘A': 'ALTERAR SENHA',
    'Error al actualizar la contraseÃ±a.': 'Erro ao atualizar a senha.',
    // Corrigir.txt - Order status texts
    'Aguardando ConfirmaÃ§Ã£o da Loja': 'Aguardando ConfirmaÃ§Ã£o da Loja',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de atÃ© 48 horas Ãºteis (atÃ© 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. VocÃª receberÃ¡ uma notificaÃ§Ã£o assim que o pedido estiver sendo preparado para envio.': 'Seu pedido foi recebido e o pagamento foi confirmado. Estamos dentro do prazo operacional de atÃ© 48 horas Ãºteis (72 horas em feriados coreanos) para separar, preparar e enviar seu produto. VocÃª receberÃ¡ uma notificaÃ§Ã£o assim que o pedido estiver sendo preparado para envio.',
  },
  en: {
    // Header
    'Belleza que nace de la tradiciÃ³n. CosmÃ©tica que transforma.': 'Beauty born from tradition. Cosmetics that transform.',
    'EnvÃ­os para toda AmÃ©rica Latina': 'Shipping throughout Latin America',
    'AtenciÃ³n': 'Support',
    'Inicio': 'Home',
    'Tienda': 'Shop',
    'Rutinas': 'Routines',
    'Blog': 'Blog',
    'Experiencias': 'Experiences',
    'Buscar...': 'Search...',
    'Entrar': 'Log In',
    'Crear Cuenta': 'Create Account',
    'Mi Panel': 'My Dashboard',
    'Cerrar SesiÃ³n': 'Log Out',
    'CategorÃ­as': 'Categories',
    'Productos': 'Products',
    'SesiÃ³n': 'Session',
    'EspaÃ±ol': 'Spanish',
    'PortuguÃ©s': 'Portuguese',
    'InglÃ©s': 'English',
    // Footer
    'Todos los derechos reservados': 'All rights reserved',
    'Orgulhosamente desenvolvido por': 'Proudly developed by',
    'En colaboraciÃ³n con': 'In collaboration with',
    // Home
    'Tu belleza.': 'Your beauty.',
    'Tu ritual.': 'Your ritual.',
    'Tu momento.': 'Your moment.',
    'CHEOTNUN â€” Tu tienda online de cosmÃ©tica coreana K-Beauty': 'CHEOTNUN â€” Your online K-Beauty store',
    'Cheotnun es tu tienda online de cosmÃ©tica coreana K-Beauty. Compra productos autÃ©nticos, descubre rutinas personalizadas para tu tipo de piel y recibe envÃ­os a toda AmÃ©rica Latina.': 'Cheotnun is your online K-Beauty store. Buy authentic Korean cosmetics, discover personalized skincare routines, and get delivery throughout Latin America.',
    'COMPRAR AHORA': 'SHOP NOW',
    'DESCUBRIR RUTINAS': 'DISCOVER ROUTINES',
    'ColecciÃ³n Curada': 'Curated Collection',
    'Descubre lo mejor del K-Beauty': 'Discover the best of K-Beauty',
    'Productos autÃ©nticos para realzar tu belleza natural.': 'Authentic products to enhance your natural beauty.',
    'VER TODAS LAS CATEGORÃAS': 'VIEW ALL CATEGORIES',
    'Favoritos de la Comunidad': 'Community Favorites',
    'MÃ¡s vendidos': 'Best Sellers',
    'Los favoritos de nuestra comunidad internacional. FÃ³rmulas probadas que entregan resultados visibles.': 'The favorites of our international community. Proven formulas that deliver visible results.',
    'VER TODOS': 'VIEW ALL',
    'Experiencias Cheotnun': 'Cheotnun Experiences',
    'Vive la belleza coreana mÃ¡s allÃ¡ de los productos': 'Experience Korean beauty beyond products',
    'SABER MÃS': 'LEARN MORE',
    'Tratamientos EspecÃ­ficos': 'Specific Treatments',
    'Rutinas para cada necesidad': 'Routines for every need',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Find the ideal routine for your skin type and lifestyle.',
    'VER TODAS LAS RUTINAS': 'VIEW ALL ROUTINES',
    'Ãšnete a nuestra comunidad': 'Join our community',
    'Tips, rutinas, lanzamientos y mucho mÃ¡s en Instagram.': 'Tips, routines, launches and much more on Instagram.',
    'SEGUIR EN INSTAGRAM': 'FOLLOW ON INSTAGRAM',
    'Ingredientes seguros': 'Safe Ingredients',
    'FÃ³rmulas efectivas': 'Effective Formulas',
    'Resultados reales': 'Real Results',
    'Inspirado en la tradiciÃ³n': 'Inspired by tradition',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'SuscrÃ­bete y recibe un 10% de descuento': 'Subscribe and get 10% off',
    'Tu correo electrÃ³nico': 'Your email',
    'SUSCRIBIRSE': 'SUBSCRIBE',
    'âœ“ Â¡Te has suscrito con Ã©xito! Bienvenido al Cheotnun Club.': 'âœ“ Successfully subscribed! Welcome to the Cheotnun Club.',
    // Tienda textos - EN
    'agregado al carrito': 'added to cart',
    'CatÃ¡logo de CosmÃ©ticos': 'Cosmetics Catalog',
    'Todas las categorÃ­as': 'All categories',
    'Todas las marcas': 'All brands',
    'Buscar Producto': 'Search Product',
    'Buscar Produto': 'Search Product',
    'Ej: SÃ©rum, Limpiador...': 'E.g: Serum, Cleanser...',
    'Marcas': 'Brands',
    'Todos los Productos': 'All Products',
    'Ordenar': 'Sort',
    'MÃ¡s Recientes': 'Most Recent',
    'Menor Precio': 'Lowest Price',
    'Mayor Precio': 'Highest Price',
    'MÃ¡s Vendidos': 'Best Sellers',
    'Agregar al Carrito': 'Add to Cart',
    'Ver Detalles': 'View Details',
    'Sin stock': 'Out of Stock',
    'CategorÃ­a': 'Category',
    'Marca': 'Brand',
    'Precio': 'Price',
    'Buscar productos...': 'Search products...',
    'No hay productos': 'No products',
    'Tu carrito estÃ¡ vacÃ­o': 'Your cart is empty',
    'Ir a la Tienda': 'Go to Shop',
    'Carrito': 'Cart',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Checkout',
    'Continuar Comprando': 'Continue Shopping',
    'Eliminar': 'Remove',
    'Cantidad': 'Quantity',
    'Total': 'Total',
    'EnvÃ­o calculado en el checkout': 'Shipping calculated at checkout',
    // Rutinas
    'Rutinas de Skincare': 'Skincare Routines',
    'Rutina de': 'Routine for',
    'Productos para': 'Products for',
    'Ver Productos': 'View Products',
    // Blog
    'Blog Cheotnun K-Beauty': 'Cheotnun K-Beauty Blog',
    'Ãšltimos ArtÃ­culos': 'Latest Articles',
    'Leer mÃ¡s': 'Read more',
    'Publicado en': 'Published on',
    'Por': 'By',
    'Volver al Blog': 'Back to Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'CHEOTNUN EXPERIENCE',
    'EN COLABORACIÃ“N CON MAEUM': 'IN COLLABORATION WITH MAEUM',
    'BEAUTY & CULTURA': 'BEAUTY & CULTURE',
    'EXPLORAR VIAJES': 'EXPLORE TRAVEL',
    'VER EXPERIENCIAS': 'VIEW EXPERIENCES',
    'Experiencias Exclusivas K-Beauty': 'Exclusive K-Beauty Experiences',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Discover the true art of Korean skincare',
    'EXPLORAR EL CATÃLOGO': 'EXPLORE THE CATALOG',
    'InmersiÃ³n y Bienestar': 'Immersion & Wellness',
    'MÃ¡s allÃ¡ del Producto:': 'Beyond the Product:',
    'Una FilosofÃ­a de Cuidado': 'A Care Philosophy',
    'Programas de InmersiÃ³n Seleccionados': 'Selected Immersion Programs',
    'Reservar Plaza': 'Reserve Spot',
    'InversiÃ³n': 'Investment',
    'Â¿Por quÃ© elegirnos?': 'Why choose us?',
    'Beneficios de la InmersiÃ³n Cheotnun': 'Benefits of Cheotnun Immersion',
    'CertificaciÃ³n Premium': 'Premium Certification',
    'InmersiÃ³n Cultural': 'Cultural Immersion',
    'AsesorÃ­a de por vida': 'Lifetime Consultation',
    'CÃ³mo participar del programa': 'How to participate in the program',
    'Paso a Paso': 'Step by Step',
    'Selecciona tu Experiencia': 'Select Your Experience',
    'Reserva & Cuestionario': 'Reservation & Questionnaire',
    'AsesorÃ­a Individual': 'Individual Consultation',
    'Vive la Experiencia': 'Live the Experience',
    'Â¿Dudas?': 'Questions?',
    'Â¿Quieres una Experiencia Privada?': 'Want a Private Experience?',
    'HABLAR CON CONSULTORA': 'TALK TO CONSULTANT',
    'Recibe invitaciones a nuevos talleres': 'Receive invitations to new workshops',
    // Dashboard
    'Mi Cuenta': 'My Account',
    'Mis Pedidos': 'My Orders',
    'Mis Favoritos': 'My Favorites',
    'Mis Datos': 'My Data',
    'Direcciones': 'Addresses',
    'Club Cheotnun': 'Cheotnun Club',
    'ConfiguraciÃ³n': 'Settings',
    'Bienvenido/a': 'Welcome',
    'Email': 'Email',
    'TelÃ©fono': 'Phone',
    'Actualizar Datos': 'Update Data',
    'Guardar': 'Save',
    'Cancelar': 'Cancel',
    'Nombre': 'Name',
    'Apellido': 'Surname',
    'Fecha de Nacimiento': 'Date of Birth',
    'GÃ©nero': 'Gender',
    'Femenino': 'Female',
    'Masculino': 'Male',
    'Otro': 'Other',
    // Auth
    'Â¿Olvidaste tu contraseÃ±a?': 'Forgot your password?',
    'Recuperar ContraseÃ±a': 'Recover Password',
    'Ingresa tu email': 'Enter your email',
    'Enviar': 'Send',
    'Volver al Login': 'Back to Login',
    'Crear tu cuenta': 'Create your account',
    'Registrarme': 'Register',
    'Ya tengo cuenta': 'I already have an account',
    'Al menos 6 caracteres': 'At least 6 characters',
    'Confirmar contraseÃ±a': 'Confirm password',
    'He leÃ­do y acepto los': 'I have read and accept the',
    'TÃ©rminos y Condiciones': 'Terms and Conditions',
    'PolÃ­tica de Privacidad': 'Privacy Policy',
    'PolÃ­tica de Cookies': 'Cookie Policy',
    // Erros e Sucesso
    'Error': 'Error',
    'Ã‰xito': 'Success',
    'Cargando...': 'Loading...',
    'Producto agregado al carrito': 'Product added to cart',
    'Producto eliminado del carrito': 'Product removed from cart',
    'Producto agregado a favoritos': 'Product added to favorites',
    'Producto eliminado de favoritos': 'Product removed from favorites',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electrÃ³nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaciÃ³n relevante sobre tus compras. Tus datos estÃ¡n seguros y nunca se comparten sin tu consentimiento.': 'When you register at Cheotnun, your data (name, email) is used to process your orders, personalize your shopping experience, and send you relevant information about your purchases. Your data is safe and never shared without your consent.',
    // Complete profile (Google OAuth)
    'Completa tu registro': 'Complete your registration',
    'Solo falta completar tus datos para finalizar tu cuenta.': 'Just fill in your details to complete your account.',
    'Guardando...': 'Saving...',
    'Completar Registro': 'Complete Registration',
    'âœ“ Registro completado!': 'âœ“ Registration complete!',
    'Erro ao salvar dados.': 'Error saving data.',
    // Recovery password
    'Nueva ContraseÃ±a': 'New Password',
    'Elige una nueva contraseÃ±a para tu cuenta.': 'Choose a new password for your account.',
    'âœ“ ContraseÃ±a actualizada. Redireccionando...': 'âœ“ Password updated. Redirecting...',
    'Actualizando...': 'Updating...',
    'CAMBIAR CONTRASEÃ‘A': 'CHANGE PASSWORD',
    'Error al actualizar la contraseÃ±a.': 'Error updating password.',
    // Corrigir.txt - Order status texts
    'Aguardando ConfirmaÃ§Ã£o da Loja': 'Awaiting Store Confirmation',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de atÃ© 48 horas Ãºteis (atÃ© 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. VocÃª receberÃ¡ uma notificaÃ§Ã£o assim que o pedido estiver sendo preparado para envio.': 'Your order has been received and payment confirmed. We are within the operational period of up to 48 business hours (72 hours on Korean holidays) to pick, prepare and ship your product. You will receive a notification as soon as your order is being prepared for shipping.',
  },
}

interface LanguageContextType {
  locale: Language
  setLocale: (l: Language) => void
  t: (key: string) => string
  isModalOpen: boolean
  setIsModalOpen: (open: boolean) => void
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Language>('pt')
  const [isModalOpen, setIsModalOpen] = useState(false)

  // Detects the best language to use based on:
  // 1. User's saved preference (localStorage) â€” highest priority
  // 2. Browser/OS language settings
  // 3. Fallback: 'pt' (PT-BR as the default for the site)
  function detectLanguage(): Language {
    // 1. Check saved user preference first
    const stored = localStorage.getItem('cheotnun_locale') as Language | null
    if (stored === 'es' || stored === 'pt' || stored === 'en') {
      return stored
    }

    // 2. Try to read from browser language settings
    // navigator.languages gives ordered list, navigator.language is the primary
    const browserLangs = typeof navigator !== 'undefined'
      ? (navigator.languages?.length ? [...navigator.languages] : [navigator.language])
      : []

    for (const lang of browserLangs) {
      if (!lang) continue
      const lower = lang.toLowerCase()
      // Portuguese variants (pt-BR, pt-PT, pt, etc.)
      if (lower.startsWith('pt')) return 'pt'
      // Spanish variants (es-ES, es-419, es-MX, es-AR, es-CO, etc.)
      if (lower.startsWith('es')) return 'es'
      // English variants (en-US, en-GB, en-AU, etc.)
      if (lower.startsWith('en')) return 'en'
    }

    // 3. Default fallback: PT-BR
    return 'pt'
  }

  useEffect(() => {
    const detected = detectLanguage()
    setLocaleState(detected)
  }, [])

  const setLocale = (l: Language) => {
    setLocaleState(l)
    localStorage.setItem('cheotnun_locale', l)
    document.cookie = `cheotnun_locale=${l};path=/;max-age=31536000;SameSite=Lax`
    setIsModalOpen(false)
  }

  const t = (key: string): string => {
    // Primeiro tenta nas traduÃ§Ãµes principais
    if (translations[locale]?.[key]) {
      return translations[locale][key]
    }
    // Depois tenta nas traduÃ§Ãµes adicionais
    if ((additionalTranslations as any)[locale]?.[key]) {
      return (additionalTranslations as any)[locale][key]
    }
    // Retorna a chave original se nÃ£o encontrar
    return key
  }

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, isModalOpen, setIsModalOpen }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
