'use client'

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'
import { additionalTranslations } from './translations'

type Language = 'es' | 'pt' | 'en'

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    'Belleza que nace de la tradici├│n. Cosm├®tica que transforma.': 'Belleza que nace de la tradici├│n. Cosm├®tica que transforma.',
    'Env├¡os para toda Am├®rica Latina': 'Env├¡os para toda Am├®rica Latina',
    'Atenci├│n': 'Atenci├│n',
    'Inicio': 'Inicio',
    'Tienda': 'Tienda',
    'Rutinas': 'Rutinas',
    'Blog': 'Blog',
    'Experiencias': 'Experiencias',
    'Buscar...': 'Buscar...',
    'Entrar': 'Iniciar Sesi├│n',
    'Crear Cuenta': 'Crear Cuenta',
    'Mi Panel': 'Mi Panel',
    'Cerrar Sesi├│n': 'Cerrar Sesi├│n',
    'Categor├¡as': 'Categor├¡as',
    'Productos': 'Productos',
    'Sesi├│n': 'Sesi├│n',
    'Espa├▒ol': 'Espa├▒ol',
    'Portugu├®s': 'Portugu├®s',
    'Ingl├®s': 'Ingl├®s',
    'Pol├¡tica de Cookies': 'Pol├¡tica de Cookies',
    // Footer
    'Todos los derechos reservados': 'Todos los derechos reservados',
    'Orgulhosamente desenvolvido por': 'Desarrollado orgullosamente por',
    'En colaboraci├│n con': 'En colaboraci├│n con',
    // Home
    'Tu belleza.': 'Tu belleza.',
    'Tu ritual.': 'Tu ritual.',
    'Tu momento.': 'Tu momento.',
    'CHEOTNUN ÔÇö Tu tienda online de cosm├®tica coreana K-Beauty': 'CHEOTNUN ÔÇö Tu tienda online de cosm├®tica coreana K-Beauty',
    'Cheotnun es tu tienda online de cosm├®tica coreana K-Beauty. Compra productos aut├®nticos, descubre rutinas personalizadas para tu tipo de piel y recibe env├¡os a toda Am├®rica Latina.': 'Cheotnun es tu tienda online de cosm├®tica coreana K-Beauty. Compra productos aut├®nticos, descubre rutinas personalizadas para tu tipo de piel y recibe env├¡os a toda Am├®rica Latina.',
    'COMPRAR AHORA': 'COMPRAR AHORA',
    'DESCUBRIR RUTINAS': 'DESCUBRIR RUTINAS',
    'Colecci├│n Curada': 'Colecci├│n Curada',
    'Descubre lo mejor del K-Beauty': 'Descubre lo mejor del K-Beauty',
    'Productos aut├®nticos para realzar tu belleza natural.': 'Productos aut├®nticos para realzar tu belleza natural.',
    'VER TODAS LAS CATEGOR├ìAS': 'VER TODAS LAS CATEGOR├ìAS',
    'Favoritos de la Comunidad': 'Favoritos de la Comunidad',
    'M├ís vendidos': 'M├ís vendidos',
    'Los favoritos de nuestra comunidad internacional. F├│rmulas probadas que entregan resultados visibles.': 'Los favoritos de nuestra comunidad internacional. F├│rmulas probadas que entregan resultados visibles.',
    'VER TODOS': 'VER TODOS',
    'Experiencias Cheotnun': 'Experiencias Cheotnun',
    'Vive la belleza coreana m├ís all├í de los productos': 'Vive la belleza coreana m├ís all├í de los productos',
    'SABER M├üS': 'SABER M├üS',
    'Tratamientos Espec├¡ficos': 'Tratamientos Espec├¡ficos',
    'Rutinas para cada necesidad': 'Rutinas para cada necesidad',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.',
    'VER TODAS LAS RUTINAS': 'VER TODAS LAS RUTINAS',
    '├Ünete a nuestra comunidad': '├Ünete a nuestra comunidad',
    'Tips, rutinas, lanzamientos y mucho m├ís en Instagram.': 'Tips, rutinas, lanzamientos y mucho m├ís en Instagram.',
    'SEGUIR EN INSTAGRAM': 'SEGUIR EN INSTAGRAM',
    'Ingredientes seguros': 'Ingredientes seguros',
    'F├│rmulas efectivas': 'F├│rmulas efectivas',
    'Resultados reales': 'Resultados reales',
    'Inspirado en la tradici├│n': 'Inspirado en la tradici├│n',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'Suscr├¡bete y recibe un 10% de descuento': 'Suscr├¡bete y recibe un 10% de descuento',
    'Tu correo electr├│nico': 'Tu correo electr├│nico',
    'SUSCRIBIRSE': 'SUSCRIBIRSE',
    'Ô£ô ┬íTe has suscrito con ├®xito! Bienvenido al Cheotnun Club.': 'Ô£ô ┬íTe has suscrito con ├®xito! Bienvenido al Cheotnun Club.',
    // Tienda
    'Tienda Cheotnun': 'Tienda Cheotnun',
    'Todos los Productos': 'Todos los Productos',
    'Filtrar': 'Filtrar',
    'Ordenar': 'Ordenar',
    'M├ís Recientes': 'M├ís Recientes',
    'Menor Precio': 'Menor Precio',
    'Mayor Precio': 'Mayor Precio',
    'M├ís Vendidos': 'M├ís Vendidos',
    'Agregar al Carrito': 'Agregar al Carrito',
    'Ver Detalles': 'Ver Detalles',
    'Sin stock': 'Sin Stock',
    'Categor├¡a': 'Categor├¡a',
    'Marca': 'Marca',
    'Precio': 'Precio',
    'Buscar productos...': 'Buscar productos...',
    'No hay productos': 'No hay productos',
    'Tu carrito est├í vac├¡o': 'Tu carrito est├í vac├¡o',
    'Ir a la Tienda': 'Ir a la Tienda',
    'Carrito': 'Carrito',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Finalizar Compra',
    'Continuar Comprando': 'Continuar Comprando',
    'Eliminar': 'Eliminar',
    'Cantidad': 'Cantidad',
    'Total': 'Total',
    'Env├¡o calculado en el checkout': 'Env├¡o calculado en el checkout',
    // Rutinas
    'Rutinas de Skincare': 'Rutinas de Skincare',
    'Rutina de': 'Rutina de',
    'Productos para': 'Productos para',
    'Ver Productos': 'Ver Productos',
    // Blog
    'Blog Cheotnun K-Beauty': 'Blog Cheotnun K-Beauty',
    '├Ültimos Art├¡culos': '├Ültimos Art├¡culos',
    'Leer m├ís': 'Leer m├ís',
    'Publicado en': 'Publicado en',
    'Por': 'Por',
    'Volver al Blog': 'Volver al Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'CHEOTNUN EXPERIENCE',
    'EN COLABORACI├ôN CON MAEUM': 'EN COLABORACI├ôN CON MAEUM',
    'BEAUTY & CULTURA': 'BEAUTY & CULTURA',
    'EXPLORAR VIAJES': 'EXPLORAR VIAJES',
    'VER EXPERIENCIAS': 'VER EXPERIENCIAS',
    'Experiencias Exclusivas K-Beauty': 'Experiencias Exclusivas K-Beauty',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Descubre el verdadero arte del skincare coreano',
    'EXPLORAR EL CAT├üLOGO': 'EXPLORAR EL CAT├üLOGO',
    'Inmersi├│n y Bienestar': 'Inmersi├│n y Bienestar',
    'M├ís all├í del Producto:': 'M├ís all├í del Producto:',
    'Una Filosof├¡a de Cuidado': 'Una Filosof├¡a de Cuidado',
    'Programas de Inmersi├│n Seleccionados': 'Programas de Inmersi├│n Seleccionados',
    'Reservar Plaza': 'Reservar Plaza',
    'Inversi├│n': 'Inversi├│n',
    '┬┐Por qu├® elegirnos?': '┬┐Por qu├® elegirnos?',
    'Beneficios de la Inmersi├│n Cheotnun': 'Beneficios de la Inmersi├│n Cheotnun',
    'Certificaci├│n Premium': 'Certificaci├│n Premium',
    'Inmersi├│n Cultural': 'Inmersi├│n Cultural',
    'Asesor├¡a de por vida': 'Asesor├¡a de por vida',
    'C├│mo participar del programa': 'C├│mo participar del programa',
    'Paso a Paso': 'Paso a Paso',
    'Selecciona tu Experiencia': 'Selecciona tu Experiencia',
    'Reserva & Cuestionario': 'Reserva & Cuestionario',
    'Asesor├¡a Individual': 'Asesor├¡a Individual',
    'Vive la Experiencia': 'Vive la Experiencia',
    '┬┐Dudas?': '┬┐Dudas?',
    '┬┐Quieres una Experiencia Privada?': '┬┐Quieres una Experiencia Privada?',
    'HABLAR CON CONSULTORA': 'HABLAR CON CONSULTORA',
    'Recibe invitaciones a nuevos talleres': 'Recibe invitaciones a nuevos talleres',
    // Dashboard
    'Mi Cuenta': 'Mi Cuenta',
    'Mis Pedidos': 'Mis Pedidos',
    'Mis Favoritos': 'Mis Favoritos',
    'Mis Datos': 'Mis Datos',
    'Direcciones': 'Direcciones',
    'Club Cheotnun': 'Club Cheotnun',
    'Configuraci├│n': 'Configuraci├│n',
    'Bienvenido/a': 'Bienvenido/a',
    'Email': 'Email',
    'Tel├®fono': 'Tel├®fono',
    'Actualizar Datos': 'Actualizar Datos',
    'Guardar': 'Guardar',
    'Cancelar': 'Cancelar',
    'Nombre': 'Nombre',
    'Apellido': 'Apellido',
    'Fecha de Nacimiento': 'Fecha de Nacimiento',
    'G├®nero': 'G├®nero',
    'Femenino': 'Femenino',
    'Masculino': 'Masculino',
    'Otro': 'Otro',
    // Auth
    '┬┐Olvidaste tu contrase├▒a?': '┬┐Olvidaste tu contrase├▒a?',
    'Recuperar Contrase├▒a': 'Recuperar Contrase├▒a',
    'Ingresa tu email': 'Ingresa tu email',
    'Enviar': 'Enviar',
    'Volver al Login': 'Volver al Login',
    'Crear tu cuenta': 'Crear tu cuenta',
    'Registrarme': 'Registrarme',
    'Ya tengo cuenta': 'Ya tengo cuenta',
    'Al menos 6 caracteres': 'Al menos 6 caracteres',
    'Confirmar contrase├▒a': 'Confirmar contrase├▒a',
    'He le├¡do y acepto los': 'He le├¡do y acepto los',
    'T├®rminos y Condiciones': 'T├®rminos y Condiciones',
    'Pol├¡tica de Privacidad': 'Pol├¡tica de Privacidad',
    // Erros e Sucesso
    'Error': 'Error',
    '├ëxito': '├ëxito',
    'Cargando...': 'Cargando...',
    'Producto agregado al carrito': 'Producto agregado al carrito',
    'Producto eliminado del carrito': 'Producto eliminado del carrito',
    'Producto agregado a favoritos': 'Producto agregado a favoritos',
    'Producto eliminado de favoritos': 'Producto eliminado de favoritos',
    // Tienda textos
    'agregado al carrito': 'agregado al carrito',
    'Cat├ílogo de Cosm├®ticos': 'Cat├ílogo de Cosm├®ticos',
    'Todas las categor├¡as': 'Todas las categor├¡as',
    'Todas las marcas': 'Todas las marcas',
    'Buscar Producto': 'Buscar Producto',
    'Ej: S├®rum, Limpiador...': 'Ej: S├®rum, Limpiador...',
    'Marcas': 'Marcas',
    'Filtrar por': 'Filtrar por',
    'Buscar Produto': 'Buscar Producto',
    'produtos': 'productos',
    'Agotado': 'Agotado',
    'VER DETALLES': 'VER DETALLES',
    'Limpiar filtro': 'Limpiar filtro',
    'Ningún producto coincide con los filtros aplicados.': 'Ningún producto coincide con los filtros aplicados.',
    'Ordenar por': 'Ordenar por',
    'Precio: Menor a Mayor': 'Precio: Menor a Mayor',
    'Precio: Mayor a Menor': 'Precio: Mayor a Menor',
    'M├ís recientes': 'M├ís recientes',
    'Nombre: A-Z': 'Nombre: A-Z',
    'Nombre: Z-A': 'Nombre: Z-A',
    'Sin resultados': 'Sin resultados',
    'No se encontraron productos': 'No se encontraron productos',
    'Intenta con otros filtros': 'Intenta con otros filtros',
    'Ver Producto': 'Ver Producto',
    'Producto': 'Producto',
    'Detalles': 'Detalles',
    'Descripci├│n': 'Descripci├│n',
    'Informaci├│n': 'Informaci├│n',
    'Ingredientes': 'Ingredientes',
    'Modo de uso': 'Modo de uso',
    'Beneficios': 'Beneficios',
    'Caracter├¡sticas': 'Caracter├¡sticas',
    'Opiniones': 'Opiniones',
    'Rese├▒as': 'Rese├▒as',
    'Calificaci├│n': 'Calificaci├│n',
    'Escribir opini├│n': 'Escribir opini├│n',
    'Enviar opini├│n': 'Enviar opini├│n',
    'Tu opini├│n': 'Tu opini├│n',
    'Opiniones de clientes': 'Opiniones de clientes',
    'Producto relacionado': 'Producto relacionado',
    'Productos relacionados': 'Productos relacionados',
    'Te puede interesar': 'Te puede interesar',
    'Ver todos': 'Ver todos',
    'Volver': 'Volver',
    'Anterior': 'Anterior',
    'Siguiente': 'Siguiente',
    'P├ígina': 'P├ígina',
    'de': 'de',
    // Header completo
    'Belleza que nace': 'Belleza que nace',
    'tradici├│n': 'tradici├│n',
    'Cosm├®tica que transforma': 'Cosm├®tica que transforma',
    'Env├¡os para toda': 'Env├¡os para toda',
    'Am├®rica Latina': 'Am├®rica Latina',
    'Buscar': 'Buscar',
    'Panel': 'Panel',
    'Salir': 'Salir',
    'Favoritos': 'Favoritos',
    'Ver carrito': 'Ver carrito',
    'Tu carrito': 'Tu carrito',
    'vac├¡o': 'vac├¡o',
    'Continuar': 'Continuar',
    'Comprar': 'Comprar',
    'Ofertas': 'Ofertas',
    'Novedades': 'Novedades',
    'Colecciones': 'Colecciones',
    'Sets': 'Sets',
    'Kits': 'Kits',
    'Regalos': 'Regalos',
    'Tarjeta Regalo': 'Tarjeta Regalo',
    'Ayuda': 'Ayuda',
    'Env├¡os': 'Env├¡os',
    'Devoluciones': 'Devoluciones',
    'FAQ': 'FAQ',
    'Contacto': 'Contacto',
    'Sobre Nosotros': 'Sobre Nosotros',
    'Nuestra Historia': 'Nuestra Historia',
    'Sostenibilidad': 'Sostenibilidad',
    'Skin Care': 'Skin Care',
    'Maquillaje': 'Maquillaje',
    'Cabello': 'Cabello',
    'Cuerpo': 'Cuerpo',
    'Solares': 'Solares',
    'Hombres': 'Hombres',
    'Ni├▒os': 'Ni├▒os',
    'Profesionales': 'Profesionales',
    'Sal├│n': 'Sal├│n',
    'Spa': 'Spa',
    // Banner Hero
    'Tu belleza': 'Tu belleza',
    'Tu ritual': 'Tu ritual',
    'Tu momento': 'Tu momento',
    'Cosm├®ticos coreanos': 'Cosm├®ticos coreanos',
    'aut├®nticos': 'aut├®nticos',
    'seleccionados': 'seleccionados',
    'cada etapa': 'cada etapa',
    'cuidado facial': 'cuidado facial',
    'F├│rmulas bot├ínicas': 'F├│rmulas bot├ínicas',
    'revelan': 'revelan',
    'luminosidad natural': 'luminosidad natural',
    'COMPRAR': 'COMPRAR',
    'AHORA': 'AHORA',
    'DESCUBRIR': 'DESCUBRIR',
    'RUTINAS': 'RUTINAS',
    // Se├º├Áes Home
    'Colecci├│n': 'Colecci├│n',
    'Curada': 'Curada',
    'Descubre': 'Descubre',
    'mejor': 'mejor',
    'K-Beauty': 'K-Beauty',
    'realzar': 'realzar',
    'belleza natural': 'belleza natural',
    'VER': 'VER',
    'TODAS': 'TODAS',
    'LAS': 'LAS',
    'CATEGOR├ìAS': 'CATEGOR├ìAS',
    'Comunidad': 'Comunidad',
    'vendidos': 'vendidos',
    'nuestra': 'nuestra',
    'internacional': 'internacional',
    'F├│rmulas probadas': 'F├│rmulas probadas',
    'entregan': 'entregan',
    'resultados': 'resultados',
    'visibles': 'visibles',
    'Vive': 'Vive',
    'belleza coreana': 'belleza coreana',
    'm├ís all├í': 'm├ís all├í',
    'productos': 'productos',
    'SABER': 'SABER',
    'M├üS': 'M├üS',
    'Tratamientos': 'Tratamientos',
    'Espec├¡ficos': 'Espec├¡ficos',
    'necesidad': 'necesidad',
    'Encuentra': 'Encuentra',
    'ideal': 'ideal',
    'tipo': 'tipo',
    'piel': 'piel',
    'estilo': 'estilo',
    'vida': 'vida',
    '├Ünete': '├Ünete',
    'comunidad': 'comunidad',
    'Tips': 'Tips',
    'rutinas': 'rutinas',
    'lanzamientos': 'lanzamientos',
    'mucho m├ís': 'mucho m├ís',
    'Instagram': 'Instagram',
    'SEGUIR': 'SEGUIR',
    'EN': 'EN',
    'INSTAGRAM': 'INSTAGRAM',
    'seguros': 'seguros',
    'F├│rmulas': 'F├│rmulas',
    'efectivas': 'efectivas',
    'Resultados': 'Resultados',
    'reales': 'reales',
    'Inspirado': 'Inspirado',
    'Cruelty': 'Cruelty',
    'Free': 'Free',
    'CHEOTNUN CLUB': 'CHEOTNUN CLUB',
    'S├®': 'S├®',
    'primera': 'primera',
    'descubrir': 'descubrir',
    'nuevos': 'nuevos',
    'ofertas': 'ofertas',
    'correo': 'correo',
    'electr├│nico': 'electr├│nico',
    '├®xito': '├®xito',
    'Bienvenido': 'Bienvenido',
    'Club': 'Club',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electr├│nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaci├│n relevante sobre tus compras. Tus datos est├ín seguros y nunca se comparten sin tu consentimiento.': 'Al registrarte en Cheotnun, tus datos (nombre, correo electr├│nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaci├│n relevante sobre tus compras. Tus datos est├ín seguros y nunca se comparten sin tu consentimiento.',
    // Complete profile (Google OAuth)
    'Completa tu registro': 'Completa tu registro',
    'Solo falta completar tus datos para finalizar tu cuenta.': 'Solo falta completar tus datos para finalizar tu cuenta.',
    'Guardando...': 'Guardando...',
    'Completar Registro': 'Completar Registro',
    'Ô£ô Registro completado!': 'Ô£ô Registro completado!',
    'Erro ao salvar dados.': 'Error al guardar los datos.',
    // Recovery password
    'Nueva Contrase├▒a': 'Nueva Contrase├▒a',
    'Elige una nueva contrase├▒a para tu cuenta.': 'Elige una nueva contrase├▒a para tu cuenta.',
    'Ô£ô Contrase├▒a actualizada. Redireccionando...': 'Ô£ô Contrase├▒a actualizada. Redireccionando...',
    'Actualizando...': 'Actualizando...',
    'CAMBIAR CONTRASE├æA': 'CAMBIAR CONTRASE├æA',
    'Error al actualizar la contrase├▒a.': 'Error al actualizar la contrase├▒a.',
    // Corrigir.txt - Order status texts
    'Aguardando Confirma├º├úo da Loja': 'Aguardando Confirmaci├│n de la Tienda',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de at├® 48 horas ├║teis (at├® 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Voc├¬ receber├í uma notifica├º├úo assim que o pedido estiver sendo preparado para envio.': 'Su pedido fue recibido y el pago fue confirmado. Estamos dentro del plazo operativo de hasta 48 horas h├íbiles (72 horas en feriados coreanos) para preparar y enviar su producto. Recibir├í una notificaci├│n cuando el pedido est├® siendo preparado para env├¡o.',
  },
  pt: {
    // Header
    'Belleza que nace de la tradici├│n. Cosm├®tica que transforma.': 'Beleza que nasce da tradi├º├úo. Cosm├®tica que transforma.',
    'Env├¡os para toda Am├®rica Latina': 'Envios para toda Am├®rica Latina',
    'Atenci├│n': 'Atendimento',
    'Inicio': 'In├¡cio',
    'Tienda': 'Loja',
    'Rutinas': 'Rotinas',
    'Blog': 'Blog',
    'Experiencias': 'Experi├¬ncias',
    'Buscar...': 'Buscar...',
    'Entrar': 'Entrar',
    'Crear Cuenta': 'Criar Conta',
    'Mi Panel': 'Meu Painel',
    'Cerrar Sesi├│n': 'Sair',
    'Categor├¡as': 'Categorias',
    'Productos': 'Produtos',
    'Sesi├│n': 'Sess├úo',
    'Espa├▒ol': 'Espanhol',
    'Portugu├®s': 'Portugu├¬s',
    'Ingl├®s': 'Ingl├¬s',
    // Footer
    'Todos los derechos reservados': 'Todos os direitos reservados',
    'Orgulhosamente desenvolvido por': 'Orgulhosamente desenvolvido por',
    'En colaboraci├│n con': 'Em colabora├º├úo com',
    // Home
    'Tu belleza.': 'Sua beleza.',
    'Tu ritual.': 'Seu ritual.',
    'Tu momento.': 'Seu momento.',
    'CHEOTNUN ÔÇö Tu tienda online de cosm├®tica coreana K-Beauty': 'CHEOTNUN ÔÇö Sua loja online de cosm├®tica coreana K-Beauty',
    'Cheotnun es tu tienda online de cosm├®tica coreana K-Beauty. Compra productos aut├®nticos, descubre rutinas personalizadas para tu tipo de piel y recibe env├¡os a toda Am├®rica Latina.': 'Cheotnun ├® sua loja online de cosm├®tica coreana K-Beauty. Compre produtos aut├¬nticos, descubra rotinas personalizadas para seu tipo de pele e receba entregas em toda a Am├®rica Latina.',
    'COMPRAR AHORA': 'COMPRAR AGORA',
    'DESCUBRIR RUTINAS': 'DESCOBRIR ROTINAS',
    'Colecci├│n Curada': 'Cole├º├úo Curada',
    'Descubre lo mejor del K-Beauty': 'Descubra o melhor do K-Beauty',
    'Productos aut├®nticos para realzar tu belleza natural.': 'Produtos aut├¬nticos para real├ºar sua beleza natural.',
    'VER TODAS LAS CATEGOR├ìAS': 'VER TODAS AS CATEGORIAS',
    'Favoritos de la Comunidad': 'Favoritos da Comunidade',
    'M├ís vendidos': 'Mais vendidos',
    'Los favoritos de nuestra comunidad internacional. F├│rmulas probadas que entregan resultados visibles.': 'Os favoritos da nossa comunidade internacional. F├│rmulas testadas que entregam resultados vis├¡veis.',
    'VER TODOS': 'VER TODOS',
    'Experiencias Cheotnun': 'Experi├¬ncias Cheotnun',
    'Vive la belleza coreana m├ís all├í de los productos': 'Viva a beleza coreana al├®m dos produtos',
    'SABER M├üS': 'SAIBA MAIS',
    'Tratamientos Espec├¡ficos': 'Tratamentos Espec├¡ficos',
    'Rutinas para cada necesidad': 'Rotinas para cada necessidade',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Encontre a rotina ideal para seu tipo de pele e estilo de vida.',
    'VER TODAS LAS RUTINAS': 'VER TODAS AS ROTINAS',
    '├Ünete a nuestra comunidad': 'Junte-se ├á nossa comunidade',
    'Tips, rutinas, lanzamientos y mucho m├ís en Instagram.': 'Dicas, rotinas, lan├ºamentos e muito mais no Instagram.',
    'SEGUIR EN INSTAGRAM': 'SEGUIR NO INSTAGRAM',
    'Ingredientes seguros': 'Ingredientes seguros',
    'F├│rmulas efectivas': 'F├│rmulas eficazes',
    'Resultados reales': 'Resultados reais',
    'Inspirado en la tradici├│n': 'Inspirado na tradi├º├úo',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'Suscr├¡bete y recibe un 10% de descuento': 'Inscreva-se e receba 10% de desconto',
    'Tu correo electr├│nico': 'Seu e-mail',
    'SUSCRIBIRSE': 'INSCREVER-SE',
    'Ô£ô ┬íTe has suscrito con ├®xito! Bienvenido al Cheotnun Club.': 'Ô£ô Inscri├º├úo realizada com sucesso! Bem-vindo ao Cheotnun Club.',
    // Tienda
    'Tienda Cheotnun': 'Loja Cheotnun',
    'Buscar Produto': 'Buscar Produto',
    'produtos': 'produtos',
    'Agotado': 'Esgotado',
    'VER DETALLES': 'VER DETALHES',
    'Limpiar filtro': 'Limpar filtro',
    'Ningún producto coincide con los filtros aplicados.': 'Nenhum produto corresponde aos filtros aplicados.',
    'Categoría Seleccionada': 'Categoria Selecionada',
    'Catálogo de Cosméticos': 'Catálogo de Cosméticos',
    'Todas las categorías': 'Todas as categorias',
    'Todas las marcas': 'Todas as marcas',
    'Buscar Producto': 'Buscar Produto',
    'Ej: Sérum, Limpiador...': 'Ex: Sérum, Limpador...',
    'Todos los Productos': 'Todos os Produtos',
    'Filtrar': 'Filtrar',
    'Ordenar': 'Ordenar',
    'M├ís Recientes': 'Mais Recentes',
    'Menor Precio': 'Menor Pre├ºo',
    'Mayor Precio': 'Maior Pre├ºo',
    'M├ís Vendidos': 'Mais Vendidos',
    'Agregar al Carrito': 'Adicionar ao Carrinho',
    'Ver Detalles': 'Ver Detalhes',
    'Sin stock': 'Sem estoque',
    'Categor├¡a': 'Categoria',
    'Marca': 'Marca',
    'Precio': 'Pre├ºo',
    'Buscar productos...': 'Buscar produtos...',
    'No hay productos': 'N├úo h├í produtos',
    'Tu carrito est├í vac├¡o': 'Seu carrinho est├í vazio',
    'Ir a la Tienda': 'Ir ├á Loja',
    'Carrito': 'Carrinho',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Finalizar Compra',
    'Continuar Comprando': 'Continuar Comprando',
    'Eliminar': 'Excluir',
    'Cantidad': 'Quantidade',
    'Total': 'Total',
    'Env├¡o calculado en el checkout': 'Frete calculado no checkout',
    // Rutinas
    'Rutinas de Skincare': 'Rotinas de Skincare',
    'Rutina de': 'Rotina de',
    'Productos para': 'Produtos para',
    'Ver Productos': 'Ver Produtos',
    // Blog
    'Blog Cheotnun K-Beauty': 'Blog Cheotnun K-Beauty',
    '├Ültimos Art├¡culos': '├Ültimos Artigos',
    'Leer m├ís': 'Ler mais',
    'Publicado en': 'Publicado em',
    'Por': 'Por',
    'Volver al Blog': 'Voltar ao Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'EXPERI├èNCIA CHEOTNUN',
    'EN COLABORACI├ôN CON MAEUM': 'EM COLABORA├ç├âO COM MAEUM',
    'BEAUTY & CULTURA': 'BELEZA & CULTURA',
    'EXPLORAR VIAJES': 'EXPLORAR VIAGENS',
    'VER EXPERIENCIAS': 'VER EXPERI├èNCIAS',
    'Experiencias Exclusivas K-Beauty': 'Experi├¬ncias Exclusivas K-Beauty',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Descubra a verdadeira arte do skincare coreano',
    'EXPLORAR EL CAT├üLOGO': 'EXPLORAR O CAT├üLOGO',
    'Inmersi├│n y Bienestar': 'Imers├úo e Bem-estar',
    'M├ís all├í del Producto:': 'Al├®m do Produto:',
    'Una Filosof├¡a de Cuidado': 'Uma Filosofia de Cuidado',
    'Programas de Inmersi├│n Seleccionados': 'Programas de Imers├úo Selecionados',
    'Reservar Plaza': 'Reservar Vaga',
    'Inversi├│n': 'Investimento',
    '┬┐Por qu├® elegirnos?': 'Por que nos escolher?',
    'Beneficios de la Inmersi├│n Cheotnun': 'Benef├¡cios da Imers├úo Cheotnun',
    'Certificaci├│n Premium': 'Certifica├º├úo Premium',
    'Inmersi├│n Cultural': 'Imers├úo Cultural',
    'Asesor├¡a de por vida': 'Assessoria vital├¡cia',
    'C├│mo participar del programa': 'Como participar do programa',
    'Paso a Paso': 'Passo a Passo',
    'Selecciona tu Experiencia': 'Selecione sua Experi├¬ncia',
    'Reserva & Cuestionario': 'Reserva & Question├írio',
    'Asesor├¡a Individual': 'Assessoria Individual',
    'Vive la Experiencia': 'Viva a Experi├¬ncia',
    '┬┐Dudas?': 'D├║vidas?',
    '┬┐Quieres una Experiencia Privada?': 'Quer uma Experi├¬ncia Privada?',
    'HABLAR CON CONSULTORA': 'FALAR COM CONSULTORA',
    'Recibe invitaciones a nuevos talleres': 'Receba convites para novos workshops',
    // Dashboard
    'Mi Cuenta': 'Minha Conta',
    'Mis Pedidos': 'Meus Pedidos',
    'Mis Favoritos': 'Meus Favoritos',
    'Mis Datos': 'Meus Dados',
    'Direcciones': 'Endere├ºos',
    'Club Cheotnun': 'Clube Cheotnun',
    'Configuraci├│n': 'Configura├º├Áes',
    'Bienvenido/a': 'Bem-vindo/a',
    'Email': 'E-mail',
    'Tel├®fono': 'Telefone',
    'Actualizar Datos': 'Atualizar Dados',
    'Guardar': 'Salvar',
    'Cancelar': 'Cancelar',
    'Nombre': 'Nome',
    'Apellido': 'Sobrenome',
    'Fecha de Nacimiento': 'Data de Nascimento',
    'G├®nero': 'G├¬nero',
    'Femenino': 'Feminino',
    'Masculino': 'Masculino',
    'Otro': 'Outro',
    // Auth
    '┬┐Olvidaste tu contrase├▒a?': 'Esqueceu sua senha?',
    'Recuperar Contrase├▒a': 'Recuperar Senha',
    'Ingresa tu email': 'Digite seu e-mail',
    'Enviar': 'Enviar',
    'Volver al Login': 'Voltar ao Login',
    'Crear tu cuenta': 'Criar sua conta',
    'Registrarme': 'Cadastrar',
    'Ya tengo cuenta': 'J├í tenho conta',
    'Al menos 6 caracteres': 'Pelo menos 6 caracteres',
    'Confirmar contrase├▒a': 'Confirmar senha',
    'He le├¡do y acepto los': 'Li e aceito os',
    'T├®rminos y Condiciones': 'Termos e Condi├º├Áes',
    'Pol├¡tica de Privacidad': 'Pol├¡tica de Privacidade',
    'Pol├¡tica de Cookies': 'Pol├¡tica de Cookies',
    // Erros e Sucesso
    'Error': 'Erro',
    '├ëxito': 'Sucesso',
    'Cargando...': 'Carregando...',
    'Producto agregado al carrito': 'Produto adicionado ao carrinho',
    'Producto eliminado del carrito': 'Produto removido do carrinho',
    'Producto agregado a favoritos': 'Produto adicionado aos favoritos',
    'Producto eliminado de favoritos': 'Produto removido dos favoritos',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electr├│nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaci├│n relevante sobre tus compras. Tus datos est├ín seguros y nunca se comparten sin tu consentimiento.': 'Ao se registrar na Cheotnun, seus dados (nome, e-mail) s├úo usados para processar seus pedidos, personalizar sua experi├¬ncia de compra e enviar informa├º├Áes relevantes sobre suas compras. Seus dados est├úo seguros e nunca s├úo compartilhados sem seu consentimento.',
    // Complete profile (Google OAuth)
    'Completa tu registro': 'Complete seu cadastro',
    'Solo falta completar tus datos para finalizar tu cuenta.': 'S├│ falta completar seus dados para finalizar sua conta.',
    'Guardando...': 'Salvando...',
    'Completar Registro': 'Completar Cadastro',
    'Ô£ô Registro completado!': 'Ô£ô Cadastro conclu├¡do!',
    'Erro ao salvar dados.': 'Erro ao salvar dados.',
    // Recovery password
    'Nueva Contrase├▒a': 'Nova Senha',
    'Elige una nueva contrase├▒a para tu cuenta.': 'Escolha uma nova senha para sua conta.',
    'Ô£ô Contrase├▒a actualizada. Redireccionando...': 'Ô£ô Senha atualizada. Redirecionando...',
    'Actualizando...': 'Atualizando...',
    'CAMBIAR CONTRASE├æA': 'ALTERAR SENHA',
    'Error al actualizar la contrase├▒a.': 'Erro ao atualizar a senha.',
    // Corrigir.txt - Order status texts
    'Aguardando Confirma├º├úo da Loja': 'Aguardando Confirma├º├úo da Loja',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de at├® 48 horas ├║teis (at├® 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Voc├¬ receber├í uma notifica├º├úo assim que o pedido estiver sendo preparado para envio.': 'Seu pedido foi recebido e o pagamento foi confirmado. Estamos dentro do prazo operacional de at├® 48 horas ├║teis (72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Voc├¬ receber├í uma notifica├º├úo assim que o pedido estiver sendo preparado para envio.',
  },
  en: {
    // Header
    'Belleza que nace de la tradici├│n. Cosm├®tica que transforma.': 'Beauty born from tradition. Cosmetics that transform.',
    'Env├¡os para toda Am├®rica Latina': 'Shipping throughout Latin America',
    'Atenci├│n': 'Support',
    'Inicio': 'Home',
    'Tienda': 'Shop',
    'Rutinas': 'Routines',
    'Blog': 'Blog',
    'Experiencias': 'Experiences',
    'Buscar...': 'Search...',
    'Entrar': 'Log In',
    'Crear Cuenta': 'Create Account',
    'Mi Panel': 'My Dashboard',
    'Cerrar Sesi├│n': 'Log Out',
    'Categor├¡as': 'Categories',
    'Productos': 'Products',
    'Sesi├│n': 'Session',
    'Espa├▒ol': 'Spanish',
    'Portugu├®s': 'Portuguese',
    'Ingl├®s': 'English',
    // Footer
    'Todos los derechos reservados': 'All rights reserved',
    'Orgulhosamente desenvolvido por': 'Proudly developed by',
    'En colaboraci├│n con': 'In collaboration with',
    // Home
    'Tu belleza.': 'Your beauty.',
    'Tu ritual.': 'Your ritual.',
    'Tu momento.': 'Your moment.',
    'CHEOTNUN ÔÇö Tu tienda online de cosm├®tica coreana K-Beauty': 'CHEOTNUN ÔÇö Your online K-Beauty store',
    'Cheotnun es tu tienda online de cosm├®tica coreana K-Beauty. Compra productos aut├®nticos, descubre rutinas personalizadas para tu tipo de piel y recibe env├¡os a toda Am├®rica Latina.': 'Cheotnun is your online K-Beauty store. Buy authentic Korean cosmetics, discover personalized skincare routines, and get delivery throughout Latin America.',
    'COMPRAR AHORA': 'SHOP NOW',
    'DESCUBRIR RUTINAS': 'DISCOVER ROUTINES',
    'Colecci├│n Curada': 'Curated Collection',
    'Descubre lo mejor del K-Beauty': 'Discover the best of K-Beauty',
    'Productos aut├®nticos para realzar tu belleza natural.': 'Authentic products to enhance your natural beauty.',
    'VER TODAS LAS CATEGOR├ìAS': 'VIEW ALL CATEGORIES',
    'Favoritos de la Comunidad': 'Community Favorites',
    'M├ís vendidos': 'Best Sellers',
    'Los favoritos de nuestra comunidad internacional. F├│rmulas probadas que entregan resultados visibles.': 'The favorites of our international community. Proven formulas that deliver visible results.',
    'VER TODOS': 'VIEW ALL',
    'Experiencias Cheotnun': 'Cheotnun Experiences',
    'Vive la belleza coreana m├ís all├í de los productos': 'Experience Korean beauty beyond products',
    'SABER M├üS': 'LEARN MORE',
    'Tratamientos Espec├¡ficos': 'Specific Treatments',
    'Rutinas para cada necesidad': 'Routines for every need',
    'Encuentra la rutina ideal para tu tipo de piel y estilo de vida.': 'Find the ideal routine for your skin type and lifestyle.',
    'VER TODAS LAS RUTINAS': 'VIEW ALL ROUTINES',
    '├Ünete a nuestra comunidad': 'Join our community',
    'Tips, rutinas, lanzamientos y mucho m├ís en Instagram.': 'Tips, routines, launches and much more on Instagram.',
    'SEGUIR EN INSTAGRAM': 'FOLLOW ON INSTAGRAM',
    'Ingredientes seguros': 'Safe Ingredients',
    'F├│rmulas efectivas': 'Effective Formulas',
    'Resultados reales': 'Real Results',
    'Inspirado en la tradici├│n': 'Inspired by tradition',
    'Cruelty Free': 'Cruelty Free',
    'Newsletter': 'Newsletter',
    'Suscr├¡bete y recibe un 10% de descuento': 'Subscribe and get 10% off',
    'Tu correo electr├│nico': 'Your email',
    'SUSCRIBIRSE': 'SUBSCRIBE',
    'Ô£ô ┬íTe has suscrito con ├®xito! Bienvenido al Cheotnun Club.': 'Ô£ô Successfully subscribed! Welcome to the Cheotnun Club.',
    // Tienda
    'Tienda Cheotnun': 'Cheotnun Shop',
    'Buscar Produto': 'Search Product',
    'produtos': 'products',
    'Agotado': 'Out of stock',
    'VER DETALLES': 'VIEW DETAILS',
    'Limpiar filtro': 'Clear filter',
    'Ningún producto coincide con los filtros aplicados.': 'No products match the applied filters.',
    'Categoría Seleccionada': 'Selected Category',
    'Catálogo de Cosméticos': 'Cosmetics Catalog',
    'Todas las categorías': 'All categories',
    'Todas las marcas': 'All brands',
    'Buscar Producto': 'Search Product',
    'Ej: Sérum, Limpiador...': 'E.g: Serum, Cleanser...',
    'Todos los Productos': 'All Products',
    'Filtrar': 'Filter',
    'Ordenar': 'Sort',
    'M├ís Recientes': 'Most Recent',
    'Menor Precio': 'Lowest Price',
    'Mayor Precio': 'Highest Price',
    'M├ís Vendidos': 'Best Sellers',
    'Agregar al Carrito': 'Add to Cart',
    'Ver Detalles': 'View Details',
    'Sin stock': 'Out of Stock',
    'Categor├¡a': 'Category',
    'Marca': 'Brand',
    'Precio': 'Price',
    'Buscar productos...': 'Search products...',
    'No hay productos': 'No products',
    'Tu carrito est├í vac├¡o': 'Your cart is empty',
    'Ir a la Tienda': 'Go to Shop',
    'Carrito': 'Cart',
    'Subtotal': 'Subtotal',
    'Finalizar Compra': 'Checkout',
    'Continuar Comprando': 'Continue Shopping',
    'Eliminar': 'Remove',
    'Cantidad': 'Quantity',
    'Total': 'Total',
    'Env├¡o calculado en el checkout': 'Shipping calculated at checkout',
    // Rutinas
    'Rutinas de Skincare': 'Skincare Routines',
    'Rutina de': 'Routine for',
    'Productos para': 'Products for',
    'Ver Productos': 'View Products',
    // Blog
    'Blog Cheotnun K-Beauty': 'Cheotnun K-Beauty Blog',
    '├Ültimos Art├¡culos': 'Latest Articles',
    'Leer m├ís': 'Read more',
    'Publicado en': 'Published on',
    'Por': 'By',
    'Volver al Blog': 'Back to Blog',
    // Experiencias
    'CHEOTNUN EXPERIENCE': 'CHEOTNUN EXPERIENCE',
    'EN COLABORACI├ôN CON MAEUM': 'IN COLLABORATION WITH MAEUM',
    'BEAUTY & CULTURA': 'BEAUTY & CULTURE',
    'EXPLORAR VIAJES': 'EXPLORE TRAVEL',
    'VER EXPERIENCIAS': 'VIEW EXPERIENCES',
    'Experiencias Exclusivas K-Beauty': 'Exclusive K-Beauty Experiences',
    'CHEOTNUN EXPERIENCES': 'CHEOTNUN EXPERIENCES',
    'Descubre el verdadero arte del skincare coreano': 'Discover the true art of Korean skincare',
    'EXPLORAR EL CAT├üLOGO': 'EXPLORE THE CATALOG',
    'Inmersi├│n y Bienestar': 'Immersion & Wellness',
    'M├ís all├í del Producto:': 'Beyond the Product:',
    'Una Filosof├¡a de Cuidado': 'A Care Philosophy',
    'Programas de Inmersi├│n Seleccionados': 'Selected Immersion Programs',
    'Reservar Plaza': 'Reserve Spot',
    'Inversi├│n': 'Investment',
    '┬┐Por qu├® elegirnos?': 'Why choose us?',
    'Beneficios de la Inmersi├│n Cheotnun': 'Benefits of Cheotnun Immersion',
    'Certificaci├│n Premium': 'Premium Certification',
    'Inmersi├│n Cultural': 'Cultural Immersion',
    'Asesor├¡a de por vida': 'Lifetime Consultation',
    'C├│mo participar del programa': 'How to participate in the program',
    'Paso a Paso': 'Step by Step',
    'Selecciona tu Experiencia': 'Select Your Experience',
    'Reserva & Cuestionario': 'Reservation & Questionnaire',
    'Asesor├¡a Individual': 'Individual Consultation',
    'Vive la Experiencia': 'Live the Experience',
    '┬┐Dudas?': 'Questions?',
    '┬┐Quieres una Experiencia Privada?': 'Want a Private Experience?',
    'HABLAR CON CONSULTORA': 'TALK TO CONSULTANT',
    'Recibe invitaciones a nuevos talleres': 'Receive invitations to new workshops',
    // Dashboard
    'Mi Cuenta': 'My Account',
    'Mis Pedidos': 'My Orders',
    'Mis Favoritos': 'My Favorites',
    'Mis Datos': 'My Data',
    'Direcciones': 'Addresses',
    'Club Cheotnun': 'Cheotnun Club',
    'Configuraci├│n': 'Settings',
    'Bienvenido/a': 'Welcome',
    'Email': 'Email',
    'Tel├®fono': 'Phone',
    'Actualizar Datos': 'Update Data',
    'Guardar': 'Save',
    'Cancelar': 'Cancel',
    'Nombre': 'Name',
    'Apellido': 'Surname',
    'Fecha de Nacimiento': 'Date of Birth',
    'G├®nero': 'Gender',
    'Femenino': 'Female',
    'Masculino': 'Male',
    'Otro': 'Other',
    // Auth
    '┬┐Olvidaste tu contrase├▒a?': 'Forgot your password?',
    'Recuperar Contrase├▒a': 'Recover Password',
    'Ingresa tu email': 'Enter your email',
    'Enviar': 'Send',
    'Volver al Login': 'Back to Login',
    'Crear tu cuenta': 'Create your account',
    'Registrarme': 'Register',
    'Ya tengo cuenta': 'I already have an account',
    'Al menos 6 caracteres': 'At least 6 characters',
    'Confirmar contrase├▒a': 'Confirm password',
    'He le├¡do y acepto los': 'I have read and accept the',
    'T├®rminos y Condiciones': 'Terms and Conditions',
    'Pol├¡tica de Privacidad': 'Privacy Policy',
    'Pol├¡tica de Cookies': 'Cookie Policy',
    // Erros e Sucesso
    'Error': 'Error',
    '├ëxito': 'Success',
    'Cargando...': 'Loading...',
    'Producto agregado al carrito': 'Product added to cart',
    'Producto eliminado del carrito': 'Product removed from cart',
    'Producto agregado a favoritos': 'Product added to favorites',
    'Producto eliminado de favoritos': 'Product removed from favorites',
    // Data transparency (Google OAuth)
    'Al registrarte en Cheotnun, tus datos (nombre, correo electr├│nico) se utilizan para procesar tus pedidos, personalizar tu experiencia de compra y enviarte informaci├│n relevante sobre tus compras. Tus datos est├ín seguros y nunca se comparten sin tu consentimiento.': 'When you register at Cheotnun, your data (name, email) is used to process your orders, personalize your shopping experience, and send you relevant information about your purchases. Your data is safe and never shared without your consent.',
    // Complete profile (Google OAuth)
    'Completa tu registro': 'Complete your registration',
    'Solo falta completar tus datos para finalizar tu cuenta.': 'Just fill in your details to complete your account.',
    'Guardando...': 'Saving...',
    'Completar Registro': 'Complete Registration',
    'Ô£ô Registro completado!': 'Ô£ô Registration complete!',
    'Erro ao salvar dados.': 'Error saving data.',
    // Recovery password
    'Nueva Contrase├▒a': 'New Password',
    'Elige una nueva contrase├▒a para tu cuenta.': 'Choose a new password for your account.',
    'Ô£ô Contrase├▒a actualizada. Redireccionando...': 'Ô£ô Password updated. Redirecting...',
    'Actualizando...': 'Updating...',
    'CAMBIAR CONTRASE├æA': 'CHANGE PASSWORD',
    'Error al actualizar la contrase├▒a.': 'Error updating password.',
    // Corrigir.txt - Order status texts
    'Aguardando Confirma├º├úo da Loja': 'Awaiting Store Confirmation',
    'Seu pedido foi recebido e o pagamento foi confirmado. Agora estamos dentro do prazo operacional de at├® 48 horas ├║teis (at├® 72 horas em feriados coreanos) para separar, preparar e enviar seu produto. Voc├¬ receber├í uma notifica├º├úo assim que o pedido estiver sendo preparado para envio.': 'Your order has been received and payment confirmed. We are within the operational period of up to 48 business hours (72 hours on Korean holidays) to pick, prepare and ship your product. You will receive a notification as soon as your order is being prepared for shipping.',
  },
}

interface LanguageContextType {
  locale: Language
  setLocale: (l: Language) => void
  t: (key: string) => string
  isModalOpen: boolean
  setIsModalOpen: (open: boolean) => void
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Language>('es')
  const [isModalOpen, setIsModalOpen] = useState(false)

  useEffect(() => {
    const stored = localStorage.getItem('cheotnun_locale') as Language | null
    if (stored === 'es' || stored === 'pt' || stored === 'en') {
      setLocaleState(stored)
    }
  }, [])

  const setLocale = (l: Language) => {
    setLocaleState(l)
    localStorage.setItem('cheotnun_locale', l)
    document.cookie = `cheotnun_locale=${l};path=/;max-age=31536000;SameSite=Lax`
    setIsModalOpen(false)
  }

  const t = (key: string): string => {
    // Primeiro tenta nas tradu├º├Áes principais
    if (translations[locale]?.[key]) {
      return translations[locale][key]
    }
    // Depois tenta nas tradu├º├Áes adicionais
    if ((additionalTranslations as any)[locale]?.[key]) {
      return (additionalTranslations as any)[locale][key]
    }
    // Retorna a chave original se n├úo encontrar
    return key
  }

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, isModalOpen, setIsModalOpen }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
